ConduitPlatform/Conduit

docker/Makefile, docker/README.md, docker/get-conduit.sh, docker/setup.sh
Before testing out `get-conduit.sh`, make sure you edit the file and set `TAG=docker` as `master` won't work before merge.
Currently hardcodes v0.10.7 for Conduit-UI.
Works around <v0.11 config restart issue using sleep, but ideally we'd be health checking the db instead.
=> Container Controller Makefile

.husky/commit-msg, commitlint.config.js, package.json, yarn.lock
Adding commit linting with commitlint and husky pre-commit hooks
=> Add commit linting & Husky

modules/database/src/admin/admin.ts
=> fix(database): non-stringified queries in getDeclaredSchemas, getDeclaredSchemasExtensions

libraries/grpc-sdk/src/interfaces/Model.ts, modules/authentication/src/models/AccessToken.schema.ts, modules/authentication/src/models/RefreshToken.schema.ts, modules/authentication/src/models/Service.schema.ts, modules/authentication/src/models/Token.schema.ts, modules/authentication/src/models/User.schema.ts, modules/chat/src/models/ChatRoom.schema.ts, modules/chat/src/models/Message.schema.ts, modules/cms/src/admin/schema.admin.ts, modules/cms/src/models/CustomEndpoints.schema.ts, modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/permissions/index.ts, modules/email/src/models/EmailTemplate.schema.ts, modules/forms/src/models/Forms.schema.ts, modules/forms/src/models/Replies.schema.ts, modules/push-notifications/src/models/NotificationToken.schema.ts, modules/storage/src/models/Container.schema.ts, modules/storage/src/models/File.schema.ts, modules/storage/src/models/Folder.schema.ts, packages/admin/src/models/Admin.schema.ts, packages/commons/src/interfaces/Model.ts, packages/config/src/models/Config.schema.ts, packages/security/src/models/Client.schema.ts
=> Fix schema permissions nesting

libraries/grpc-sdk/package.json, libraries/grpc-sdk/src/classes/RoutingManager.ts, libraries/grpc-sdk/src/classes/index.ts, libraries/grpc-sdk/src/helpers/RoutingJsonConstructor.ts, libraries/grpc-sdk/src/helpers/RoutingUtilities.ts, libraries/grpc-sdk/src/helpers/wrapRouterFunctions.ts, libraries/grpc-sdk/src/interfaces/Middleware.ts, libraries/grpc-sdk/src/modules/router/index.ts, libraries/grpc-sdk/src/types/index.ts, modules/authentication/src/routes/routes.ts, modules/email/src/email-provider/interfaces/TemplateOptions.ts, modules/email/src/email-provider/transports/mailgun/mailgunMailBuilder.ts, modules/email/src/email-provider/transports/mandrill/mandrillBuilder.ts, modules/email/src/email-provider/transports/sendgrid/sendgridMailBuilder.ts, modules/email/src/services/email.service.ts, yarn.lock
This PR's goals are to create a better and more friendlier way of registering routes when using the grpc-sdk. Specifically it adds the RoutingManager class which also contains a builder class for an even more "elegant" way of registering rotes.
Also, it contains a refactor removing various functions that provide abstractions from the router grpc client, to cleanup the client it self and create better functions, that will allow devs to choose the right path for them.
Basically the ways that you will be able to register a route:
- Using a .protofile and plain grpc handlers with (call,callback) signature
- No grpc file but with either (call,callback) or (request)=>promise signatures (cannot mix)
- Routing Manager with (request)=>promise signature
- Route builder with (request)=>promise …
=> Routing improvements

libraries/grpc-sdk/src/modules/databaseProvider/index.ts, modules/cms/src/admin/admin.ts, modules/cms/src/admin/schema.admin.ts, modules/database/src/DatabaseProvider.ts, modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/adapters/utils/extensions.ts, modules/database/src/admin/admin.ts, modules/database/src/database-provider.proto, modules/database/src/interfaces/DeclaredSchema.ts, modules/database/src/interfaces/DeclaredSchemaExtension.ts, modules/database/src/interfaces/index.ts, modules/database/src/models/DeclaredSchema.schema.ts
=> feat(database,cms,grpc-sdk): schema extensions

libraries/grpc-sdk/src/classes/ConduitSchemaExtension.ts, libraries/grpc-sdk/src/classes/index.ts, libraries/grpc-sdk/src/modules/databaseProvider/index.ts, modules/cms/src/admin/schema.admin.ts, modules/database/src/DatabaseProvider.ts, modules/database/src/database-provider.proto, modules/database/src/types.ts
Minor improvement over gRPC request types
- [] Refactor
=> chore(grpc-sdk,database,cms): setSchemaExtension gRPC cleanup

modules/authentication/src/handlers/AuthenticationProviders/OAuth2.ts, modules/authentication/src/handlers/facebook/facebook.ts, modules/authentication/src/models/User.schema.ts
Feat: #33 
A new field  `data: { type: TYPE.JSON }` added in the User.Schema. By doing this , when authenticating with a third party provider the user metadata will be stored in the database.
=> Storing  metadata information 

modules/cms/src/admin/admin.ts, modules/cms/src/admin/customEndpoints/customEndpoints.admin.ts
Adds a schema name based array filter to CMS.getCustomEndpoints.
=> feat(cms): getCustomEndpoints schemaName array filter

modules/authentication/src/handlers/phone.ts, modules/authentication/src/utils/auth.ts
=> fix(authentication): ConfigController import

libraries/grpc-sdk/src/classes/ManagedModule.ts, modules/authentication/src/Authentication.ts, modules/email/src/Email.ts, modules/email/src/index.ts
=> ManagedModule Refactor for Email

libraries/grpc-sdk/src/classes/ModuleManager.ts
=> fix(grpc-sdk): scope resolution in promise

modules/forms/src/Forms.ts, modules/forms/src/admin/admin.ts, modules/forms/src/index.ts
Followup of #44.
Also fixes GetFormReplies expecting form id as a query param.
GetFormReplies now properly accepts form id as a url param.
=> ManagedModule Refactor for Forms

modules/authentication/src/Authentication.ts, modules/chat/src/Chat.ts, modules/chat/src/index.ts
=> ManagedModule Refactor for Chat

libraries/grpc-sdk/src/classes/ConduitModule.ts, libraries/grpc-sdk/src/index.ts
This PR contains sdk code to support importing conduit modules when you have their ts-proto or protobuf definitions. 
This will allow modules to use modules that are not pre-packaged in the sdk, and also allow us to cleanup the SDK and remove non-core modules from being packaged, reducing the size of the distributable as well as reducing overall complexity.
=> Dynamic GRPC modules

libraries/grpc-sdk/src/index.ts, modules/database/src/Database.ts, modules/database/src/migrations/cmsOwners.migration.ts
fix(database): schema migrations from CMS not working properly
fix(grpc-sdk): module names weren't used correctly
refactor(database): wrongful rename of main module
=> V0.12 issues fix

modules/authentication/src/handlers/local.ts
=> fix(authentication): local auth not enabled due to config field typo

libraries/grpc-sdk/src/helpers/RoutingUtilities.ts, modules/authentication/src/handlers/local.ts
=> v0.11 backport fixes (authentication, grpc-sdk)

libraries/grpc-sdk/src/classes/ModuleManager.ts, modules/sms/src/Sms.ts, modules/sms/src/index.ts
=> ManagedModule Refactor for SMS

libraries/grpc-sdk/src/modules/chat/index.ts, modules/chat/src/Chat.ts, modules/chat/src/index.ts, modules/email/src/Email.ts, modules/email/src/index.ts, modules/forms/src/Forms.ts, modules/forms/src/index.ts
=> Fix Chat's setConfig returning stringified JSON

modules/push-notifications/src/PushNotifications.ts, modules/push-notifications/src/admin/admin.ts, modules/push-notifications/src/index.ts, modules/push-notifications/src/routes/routes.ts
Followup of #44 + bug fixes:
- setNotificationToken route crashing due to missing user in context after not passing through auth middleware.
- setNotification passing empty 'sendTo' field to provider
=> ManagedModule Refactor for PushNotifications

packages/router/src/controllers/GraphQl/GraphQL.ts
=> fix(router): GraphQL delays due to repetitive refreshes

modules/email/src/email-provider/index.ts, modules/email/src/email-provider/interfaces/Template.ts, modules/email/src/email-provider/interfaces/mailgun/MailgunTemplate.ts, modules/email/src/email-provider/interfaces/mandrill/MandrillTemplate.ts, modules/email/src/email-provider/interfaces/sendgrid/SendgridTemplate.ts, modules/email/src/email-provider/models/EmailProviderClass.ts, modules/email/src/email-provider/transports/mailgun/MailgunProvider.ts, modules/email/src/email-provider/transports/mandrill/MandrilProvider.ts, modules/email/src/email-provider/transports/sendgrid/SendgridProvider.ts
**Information:**
Closes #69 
- Made interfaces which mirror the returned fields of each email provider Templates.
=> Template interfaces 

docker/Makefile
Container Makefile controller update for Conduit 0.12.2.
=> chore: update Makefile for v0.12.2

modules/storage/src/handlers/file.ts
Backport from #75 to Conduit v0.11.
=> fix(storage): store() call missing isPublic arg in createFile handler

modules/database/src/adapters/DatabaseAdapter.ts
Removed a non-breaking redundant async from synchronous function definition.
=> chore(database): remove redundant async

docker/Makefile
-Bumped Conduit version from v0.12.2 to v0.12.3.
-Fixed PostgreSQL
-Overall improvements
Most notably, upgrading to v0.12.3 should greatly improve interaction with the Admin Swagger.
Container Makefile related changes, fixes and updates.
=> Makefile updates (v0.12.3)

packages/admin/src/index.ts, packages/router/src/controllers/Rest/Rest.ts
=> fix(router,admin): admin requests not passing through master key middleware

README.md
**What kind of change does this PR introduce?**
Minor updates to the core readme file, mainly around env vars.
=> chore: update core readme

libraries/grpc-sdk/src/classes/Routing/RoutingManager.ts, modules/database/src/controllers/customEndpoints/customEndpoint.controller.ts, modules/database/src/controllers/customEndpoints/utils.ts, modules/database/src/routes/routes.ts
This PR fixes a bug where custom endpoint handlers were not assigned properly in the route builder.
=> Custom endoints build

modules/database/src/controllers/customEndpoints/customEndpoint.controller.ts, modules/database/src/controllers/customEndpoints/utils.ts, modules/database/src/routes/routes.ts
This PR fixes a bug where custom endpoint handlers were not assigned properly in the route builder.
This a reopening of #94 .
=> fix(database): createCustomEndpointRoute argument type changed

modules/chat/src/routes/routes.ts
Fixes:
- `createRoom` app route not requiring `roomName`
- `addUserToRoom` app route not updating room document
Removed unnecessary type casts.
Cleaned up route field types
=> fix(chat): createRoom, addUserToRoom app routes

docker/Makefile
Updated Makefile Conduit and Conduit-UI default tags.
Updated Makefile container version tags.
=> chore(containers): bump Makefile tags to 0.12.6/0.12.2

libraries/grpc-sdk/src/modules/pushNotifications/index.ts, modules/push-notifications/src/PushNotifications.ts, modules/push-notifications/src/interfaces/IPushNotificationsProvider.ts, modules/push-notifications/src/providers/Firebase.provider.ts, modules/push-notifications/src/push-notifications.proto, modules/push-notifications/src/types/index.ts
This PR introduces  an gRPC call.
**sendNotification** rpc service is implemented.
```tsx
service PushNotifications {
rpc SetConfig(SetConfigRequest) returns (SetConfigResponse);
rpc SetNotificationToken(SetNotificationTokenRequest) returns (SetNotificationTokenResponse);
rpc GetNotificationTokens(GetNotificationTokensRequest) returns (GetNotificationTokensResponse);
rpc SendNotification(SendNotificationRequest) returns (SendNotificationResponse); // new feature
}
```
=> Grpc send notification

libraries/grpc-sdk/src/modules/core/index.ts, modules/chat/src/Chat.ts, modules/chat/src/config/config.ts, modules/chat/src/models/InvitationToken.schema.ts, modules/chat/src/models/index.ts, modules/chat/src/routes/InvitationRoutes.ts, modules/chat/src/routes/routes.ts, modules/chat/src/templates/ChatRoomInvitation.ts, modules/chat/src/templates/index.ts, modules/chat/src/utils/index.ts
Solves the issue #116 
The PR introduces invitation strategy on the chat rooms.
A client can either accept or decline an invitation if the module is configured to do this.
- Chat Configuration changed to ->
```   
sendInvitations: {
enabled: {
doc: 'Defines if this strategy is active or not',
format: 'Boolean',
default: false,
},
send_email: {
doc: 'Defines if the sender should automatically send an invitation e-mail to the user',
format: 'Boolean',
default: false,
}
}
```
=> Chat room invitation

modules/authentication/src/handlers/AuthenticationProviders/OAuth2.ts, modules/authentication/src/handlers/local.ts
Replaced a hardcoded Conduit URL.
=> fix(authentication): replace hardcoded Conduit url

packages/security/src/handlers/client-validation/index.ts, packages/security/src/utils/security.ts
Domain check was not proper when client validation was enabled.
=> Client checks

modules/authentication/src/config/config.ts, modules/authentication/src/handlers/common.ts, modules/authentication/src/handlers/local.ts, modules/authentication/src/utils/auth.ts
This PR introduces Session management in authentication module.
Now, it can be configured when login's from multiple clients are allowed.
Also it can be configured whenever someone can log in from the same client multiple times.
Confiration additions:
```tsx
clients: {
multipleUserSessions: {
doc: 'Defines if a user can login multiple times from a single client',
format: 'Boolean',
default: false,
},
multipleClientLogins: {
doc: 'Defines if a user can be logged in from multiple clients',
format: 'Boolean',
default: true,
},
}
```
=> feat(authentication): logins and logouts from multiple clients etc

Dockerfile, modules/authentication/Dockerfile, modules/chat/Dockerfile, modules/database/Dockerfile, modules/email/Dockerfile, modules/forms/Dockerfile, modules/push-notifications/Dockerfile, modules/sms/Dockerfile, modules/storage/Dockerfile, packages/Dockerfile
refactor: add yarn cache clean to reduce yarn cache sizes
closes #143 
=> refactor: improve Dockerfile layers to decrease size

libraries/grpc-sdk/src/helpers/wrapRouterFunctions.ts
=> fix(grpc-sdk): wrapRouterFunctions request logging

packages/security/src/admin/routes/CreateSecurityClient.route.ts
Domain checks applied in client validation.
=> fix(security): domain regex checks

packages/security/src/admin/routes/CreateSecurityClient.route.ts
Specific check case where domain equals to '*'  added when generating WEB client.
=> fix(security): specific case for domain

modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/permissions/index.ts
Backwards compatibility cleanup.
=> chore(database): cleanup leftover backwards compatibility code

libraries/grpc-sdk/src/modules/config/index.ts, libraries/grpc-sdk/src/modules/database/index.ts, libraries/grpc-sdk/src/utilities/StateManager.ts, modules/authentication/src/handlers/AuthenticationProviders/OAuth2.ts, modules/authentication/src/handlers/AuthenticationProviders/interfaces/AuthParams.ts, modules/authentication/src/handlers/AuthenticationProviders/interfaces/RedirectOptions.ts, modules/database/src/Database.ts, modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts, modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/utils.ts, modules/database/src/adapters/utils/extensions.ts, modules/database/src/admin/schema.admin.ts, modules/database/src/controllers/cms/schema.controller.ts, modules/database/src/controllers/customEndpoints/customEndpoint.controller.ts, modules/database/src/handlers/cms.handler.ts, modules/database/src/interfaces/ConduitDatabaseSchema.ts, modules/database/src/interfaces/SchemaAdapter.ts, packages/commons/src/utilities/StateManager.ts
Explicit "any" types in authentication, database, grpc-sdk, commons  removed or replaced with new types/interfaces.
=> Replace Explicit Any Types

libraries/grpc-sdk/src/helpers/wrapRouterFunctions.ts, libraries/grpc-sdk/src/modules/admin/index.ts, packages/core/src/HttpServer.ts, packages/router/package.json, packages/router/src/controllers/GraphQl/GraphQL.ts, packages/router/src/controllers/Rest/Rest.ts, packages/router/src/controllers/Router.ts, packages/router/src/controllers/Routing.ts, packages/router/src/index.ts, yarn.lock
=> refactor(router):  re-work refresh functions to improve performance for large amounts of registered routes

modules/database/src/migrations/crudOperations.migration.ts
crudOperations migration was running multiple times. This PR fixes this bug.
=> fix(database): crudOperations migration

modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/introspection/mongoose/utils.ts
This PR fixes an issue where the extracted array type in Mongoose is "Array".
=> fix(database): array type not extracted properly

modules/authentication/src/handlers/oauth2/OAuth2.ts, modules/authentication/src/handlers/oauth2/facebook/facebook.ts, modules/authentication/src/handlers/oauth2/figma/figma.ts, modules/authentication/src/handlers/oauth2/github/github.ts, modules/authentication/src/handlers/oauth2/google/google.ts, modules/authentication/src/handlers/oauth2/interfaces/MakeRequest.ts, modules/authentication/src/handlers/oauth2/microsoft/microsoft.ts, modules/authentication/src/handlers/oauth2/slack/slack.ts, modules/authentication/src/handlers/oauth2/twitch/twitch.ts
=> refactor(authentication): simplify oAuth2 provider implementation

modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/controllers/cms/utils.ts
fix(database): put crud operation not properly checked
=> fix(database): collections found as foreign when missing collectionName

modules/database/src/admin/schema.admin.ts
Previously, any schema object submitted to `finalizeSchemas()` would more or less be accepted by the handler.
If anyone were to accidentally send a schema omitting some of the `PendingSchema` `schemaOption` defaults (`crudOperations`, `permissions`, `noSync` and `imported`) we wouldn't update these while going through the adapters.
Alternatively, we could throw an error or move the deep object merging to the abstract adapter.
=> fix(database): pending schemas import safe defaults in finalizeSchemas()

modules/authentication/Dockerfile
=> build(authentication): change python2 which is now deprecated in alpine

.eslintrc.json
=> ci: eslintrc no-unused-vars.ignoreRestSiblings true

modules/database/src/admin/index.ts, modules/database/src/admin/schema.admin.ts
=> fix(database): wrong introspection counts

packages/admin/package.json, packages/admin/src/index.ts, yarn.lock
Adds `helmet` to Conduit Admin.
=> feat(admin): Helmet middleware

modules/router/src/Router.ts
=> fix(router): not registering SetConfig rpc

libraries/grpc-sdk/src/index.ts
=> fix(grpc-sdk): module connectivity reporting

modules/storage/src/Storage.ts
=> fix(storage): registering routes while disabled

modules/database/src/Database.ts, modules/database/src/controllers/cms/schema.controller.ts, modules/database/src/controllers/customEndpoints/customEndpoint.controller.ts
=> Database admin routes register without router

modules/forms/src/Forms.ts, modules/forms/src/controllers/forms.controller.ts
=> refactor(forms): decouple form controller and admin router from router fixes #229

docker/docker-compose.yml
=> build: fix env names (v0.13)

docker/docker-compose.yml
=> build: fix env names (v0.12)

packages/admin/src/index.ts, packages/admin/src/middleware/Admin.middleware.ts, packages/admin/src/middleware/Auth.middleware.ts
=> chore(admin): remove admin prefix from REST routes

modules/database/src/adapters/mongoose-adapter/utils.ts, modules/database/src/adapters/sequelize-adapter/utils.ts
=> fix(database): createWithPopulations looking for wrong properties

modules/database/src/adapters/sequelize-adapter/index.ts
=> fix(database): get pending schema model based on collection name

docker/docker-compose.yml
Fixes Conduit UI resolution of Conduit Admin's REST API.
=> build: fix compose file ui CONDUIT_URL env var

modules/router/src/Router.ts, modules/router/src/config/config.ts, packages/admin/package.json, packages/admin/src/config/config.ts, packages/admin/src/index.ts, packages/admin/src/routes/Login.route.ts, packages/admin/src/utils/config.ts, yarn.lock
This PR adds support for generating config defaults for hostUrl and tokenSecret in case they are not provided in set config.
- [] Yes
=> Default Router & Admin Config Values

libraries/grpc-sdk/package.json, libraries/grpc-sdk/src/index.ts, libraries/grpc-sdk/src/utilities/Logger.ts, libraries/hermes/src/index.ts, libraries/hermes/src/utils/logger.ts, yarn.lock
=> feat(grpc-sdk): add support for logging to Grafana Loki

packages/core/src/config-manager/service-discovery/index.ts
=> fix(core): service discovery registering new modules as serving

modules/authentication/src/admin/index.ts, modules/authentication/src/handlers/local.ts
Gonna submit backport fixes to affected branches soon, together with #250 fixes and anything else that may come up.
=> fix(authentication): user model dropping hashedPassword due to object ref deletion

README.md, modules/database/package.json
=> Remove Packages for Unsupported SQL Databases

libraries/grpc-sdk/src/index.ts
=> Add Module Instance Id to Loki Logger

modules/router/src/security/index.ts, packages/admin/src/index.ts
=> fix(admin,router): helmet blocking slash-suffixed GraphQL endpoints

modules/authentication/src/handlers/local.ts
Resend verification email when creating a new user
=> feat(authentication): resend verification email 

packages/core/src/config-manager/admin/routes/SetConfigRoute.ts
=> fix(core): config set not working

modules/authentication/src/handlers/local.ts
=> refactor(authentication): email verification link rework

modules/database/src/Database.ts, modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts
=> chore(database): typo in function name

packages/core/src/config-manager/index.ts
=> fix(core): fix configureModule not passing schema to register routes

packages/admin/src/index.ts, packages/core/src/config-manager/index.ts
fix(admin): admin config update inconsistency
=> fix(core): admin config update channel inconsistency

modules/sms/src/Sms.ts
=> fix(sms): not starting up with invalid config

libraries/grpc-sdk/src/helpers/wrapGrpcFunctions.ts
=> feat(grpc-sdk): try/catch in wrapGrpcFunctions to wrap function calls

modules/authentication/src/handlers/local.ts, modules/authentication/src/handlers/phone.ts, modules/authentication/src/handlers/service.ts, modules/authentication/src/utils/auth.ts
Some cleanups to make code factor happier :)
=> Code factor refactors

modules/email/src/admin/index.ts, modules/email/src/email-provider/transports/mailgun/MailgunProvider.ts, modules/email/src/email-provider/transports/mandrill/MandrilProvider.ts, modules/email/src/email-provider/transports/sendgrid/SendgridProvider.ts, modules/email/src/email-provider/utils/getHandleBarsValues.ts, modules/email/src/email-provider/utils/htmlCheck.ts, modules/email/src/email-provider/utils/index.ts, modules/email/src/parse-test/getHBValues.ts
=> chore(email): remove duplicate file

modules/database/src/admin/customEndpoints/customEndpoints.admin.ts, modules/database/src/admin/customEndpoints/utils.ts
=> refactor(database): admin custom endpoints methods rework for code factor

CHANGELOG.md, libraries/grpc-sdk/package.json, package.json
=> Release fix

libraries/grpc-sdk/src/classes/HealthCheck.ts, libraries/hermes/src/Router.ts, libraries/hermes/src/utils/GrpcConverter.ts, modules/authentication/src/handlers/oauth2/twitch/twitch.ts, modules/authentication/src/routes/index.ts, modules/database/src/admin/documents.admin.ts, modules/email/src/admin/index.ts, modules/email/src/email-provider/transports/sendgrid/SendgridProvider.ts, packages/admin/src/index.ts, packages/core/src/config-manager/config-storage/index.ts
=> chore(grpc-sdk,hermes,authentication,database,email,admin,core): set const instead of let

modules/forms/src/admin/index.ts
=> fix(forms): getForms count not using search query

modules/database/src/adapters/DatabaseAdapter.ts
=> fix(database): createSchemaFromAdapter() crashing for non-registered schemas

modules/email/src/services/email.service.ts
**Minor bug fixed:**
The sender of the email was being set twice and as a result it could be set to null after a previous if check
=> refactor(email): sendEmail complexity

modules/forms/src/admin/index.ts
=> refactor(forms): duplicate code rework

modules/authentication/src/admin/index.ts, modules/authentication/src/admin/user.ts, modules/sms/src/providers/twilio.ts
=> fix(authentication):  twoFaMethod missing param

libraries/grpc-sdk/src/classes/Routing/RoutingManager.ts
=> refactor(grpc-sdk): routing manager duplicate code rework

packages/core/src/config-manager/service-discovery/index.ts
Return type in moduleExists() fixed.
=> fix(core): module exist grpc function return type fixed

modules/authentication/src/handlers/local.ts
=> Fix(authentication): get to post request in verify-qr-code endpoint

libraries/grpc-sdk/src/modules/config/index.ts, packages/core/src/config-manager/index.ts, packages/core/src/core.proto
addFieldsToConfig() and updateConfig()  gRPC functions removed from sdk and config package
=> refactor(core,grpc-sdk)!: remove deprecated gRPC functions

packages/admin/package.json
=> fix(admin): add package node2fa

packages/admin/src/index.ts, packages/admin/src/migrations/migrateIsSuperAdminToAdmin.ts
=> fix(admin): super admin migration

modules/authentication/src/handlers/local.ts
Set time window to 1min instead of 4min for app routes
=> feat(authentication): change verification time window for qr tokens

packages/admin/src/index.ts, packages/admin/src/middleware/Auth.middleware.ts, packages/admin/src/routes/Login.route.ts, packages/admin/src/routes/VerifyTwoFa.route.ts, packages/admin/src/utils/auth.ts
=> fix(admin): token in verify2fa

packages/admin/src/index.ts
=> fix(admin): crashing on disabled metrics

packages/admin/src/routes/VerifyQrCode.route.ts
=> fix(admin): verifyTwoFactorToken missing window param

packages/admin/src/routes/Login.route.ts
=> fix(admin): temporary token expiration time

modules/database/src/Database.ts, modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts
Fixes a bug where Database would not register its own schemas on the very first run (introduced in #332).
Cleans up adapter initialization, simplifies `createSchemaFromAdapter()` calls by internalizing `cndPrefix` argument.
=> fix(database): initial db schema registration

modules/storage/src/Storage.ts
=> fix(storage): initialize metrics assuming files exist

modules/authentication/src/Authentication.ts, modules/authentication/src/handlers/local.ts, modules/authentication/src/handlers/phone.ts, modules/authentication/src/routes/index.ts, modules/push-notifications/src/PushNotifications.ts
Simplify sms, email, router monitoring and fix for push-notifications config crash.
=> fix(authentication): simplify monitors

modules/authentication/src/Authentication.ts, modules/authentication/src/handlers/local.ts, modules/authentication/src/handlers/oauth2/OAuth2.ts, modules/authentication/src/handlers/phone.ts, modules/authentication/src/handlers/tokenProvider.ts, modules/authentication/src/handlers/twoFa.ts, modules/authentication/src/utils/auth.ts
This PR introduces the above changes:
- Split Auth utils verifyCode() function 
- Change forgotten userIds 
- Remove unnecessary awaits
- Fix bug constructCookies function in tokenProvider accessing an undefined refreshToken
=> fix(authentication): auth refactor changes

modules/authentication/src/Authentication.ts, modules/authentication/src/handlers/common.ts, modules/authentication/src/handlers/tokenProvider.ts, modules/authentication/src/handlers/twoFa.ts, modules/authentication/src/routes/middleware.ts
- Adds check in config for valid cookieOptions maxAge
- Fixes functions setting old config cookieOptions
- Adds new 2FA route
=> refactor(authentication): auth refactor changes and fixes

modules/authentication/src/admin/index.ts, modules/database/src/admin/index.ts
=> fix(authentication,database): admin route definition handler binds

modules/email/src/admin/index.ts, modules/email/src/models/EmailTemplate.schema.ts, modules/email/src/services/email.service.ts
=> chore(email): subject field required

modules/database/src/admin/customEndpoints/customEndpoints.admin.ts, modules/database/src/admin/index.ts
Minor response object formatting improvement.
=> chore(database): improve schema operation details admin route response signature

libraries/grpc-sdk/src/routing/RoutingManager.ts, libraries/grpc-sdk/src/routing/RoutingUtilities.ts
=> fix(grpc-sdk): admin_grpc_requests_total metric

libraries/grpc-sdk/src/classes/ConduitModule.ts, libraries/grpc-sdk/src/index.ts
=> feat(grpc-sdk): client connection logs

libraries/grpc-sdk/src/classes/ConduitModule.ts, libraries/grpc-sdk/src/metrics/clientMiddleware.ts
=> fix(grpc-sdk): gRPC request retries for cancelled/aborted requests

packages/core/src/config-manager/admin/routes/SetConfigRoute.ts
Fixes module config PATCHes (regressed in #383).
=> fix(core): module config patch

modules/push-notifications/src/PushNotifications.ts, modules/sms/src/Sms.ts
=> fix(push-notifications,sms): health status

modules/authentication/README.mdx, modules/authentication/src/models/User.schema.ts, modules/chat/src/models/User.model.ts, modules/push-notifications/src/models/User.model.ts
=> fix(authentication): drop Kakao login leftovers

modules/email/src/Email.ts, modules/forms/src/Forms.ts
Event based syncs like this are no longer required.
=> fix(email,forms): replace Forms event-based Email health sync

libraries/grpc-sdk/src/index.ts, packages/core/src/config-manager/service-discovery/index.ts
Fixes module update events (regressed in #383).
=> fix(core): service discovery not emitting update events on module health updates

modules/authentication/src/handlers/oauth2/OAuth2.ts, modules/authentication/src/handlers/oauth2/facebook/facebook.ts, modules/authentication/src/handlers/oauth2/figma/figma.ts, modules/authentication/src/handlers/oauth2/github/github.ts, modules/authentication/src/handlers/oauth2/gitlab/gitlab.ts, modules/authentication/src/handlers/oauth2/google/google.ts, modules/authentication/src/handlers/oauth2/interfaces/OAuth2Settings.ts, modules/authentication/src/handlers/oauth2/microsoft/microsoft.ts, modules/authentication/src/handlers/oauth2/slack/slack.ts, modules/authentication/src/handlers/oauth2/twitch/twitch.ts, modules/authentication/src/routes/index.ts
=> fix(authentication): redirectUrl from router only set once

modules/authentication/src/config/index.ts, modules/authentication/src/config/linkedIn.config.ts, modules/authentication/src/handlers/oauth2/OAuth2.ts, modules/authentication/src/handlers/oauth2/index.ts, modules/authentication/src/handlers/oauth2/linkedIn/linkedin.json, modules/authentication/src/handlers/oauth2/linkedIn/linkedin.ts, modules/authentication/src/handlers/oauth2/linkedIn/linkedin.user.ts
=> feat(authentication): linkedIn-provider

modules/authentication/src/config/bitbucket.config.ts, modules/authentication/src/config/index.ts, modules/authentication/src/handlers/oauth2/bitbucket/bitbucket.json, modules/authentication/src/handlers/oauth2/bitbucket/bitbucket.ts, modules/authentication/src/handlers/oauth2/bitbucket/bitbucket.user.ts, modules/authentication/src/handlers/oauth2/index.ts
=> feat(authentication): bitbucket-provider

modules/authentication/src/config/index.ts, modules/authentication/src/config/reddit.config.ts, modules/authentication/src/handlers/oauth2/OAuth2.ts, modules/authentication/src/handlers/oauth2/index.ts, modules/authentication/src/handlers/oauth2/reddit/reddit.json, modules/authentication/src/handlers/oauth2/reddit/reddit.ts, modules/authentication/src/handlers/oauth2/reddit/reddit.user.ts
=> feat(authentication): reddit provider

packages/core/src/config-manager/config-storage/index.ts, packages/core/src/config-manager/migrations/index.ts, packages/core/src/config-manager/migrations/migrateConfig.ts, packages/core/src/config-manager/models/Config.schema.ts, packages/core/tsconfig.json
=> refactor(core): config refactor

modules/authentication/package.json, modules/authentication/src/config/index.ts, modules/authentication/src/config/twitter.config.ts, modules/authentication/src/handlers/oauth2/OAuth2.ts, modules/authentication/src/handlers/oauth2/index.ts, modules/authentication/src/handlers/oauth2/interfaces/AuthParams.ts, modules/authentication/src/handlers/oauth2/interfaces/OAuth2Settings.ts, modules/authentication/src/handlers/oauth2/interfaces/RedirectOptions.ts, modules/authentication/src/handlers/oauth2/twitter/twitter.json, modules/authentication/src/handlers/oauth2/twitter/twitter.ts, modules/authentication/src/handlers/oauth2/twitter/twitter.user.ts
=> feat(authentication): twitter provider

packages/core/src/config-manager/config-storage/index.ts
Fixes wrong config being updated introduced in #399 
=> fix(core): fix config bug

modules/authentication/src/routes/middleware.ts
=> fix(authentication): auth middleware excluded paths

modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts, modules/database/src/adapters/sequelize-adapter/utils.ts
This is the patchiest of patches. It doesn't solve any longterm problems.
This provides some stability until we figure out a better approach for MongoDB/PostgreSQL interoperability.
=> fix(database): failing $exists and nullity queries in postgres

modules/database/src/routes/index.ts
This PR fixes a bug where custom endpoints would not get registered in the `Router` while there were no registered CRUD endpoints.
=> fix(database): custom endpoints not registering without CRUD endpoints

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml
=> chore: GitHub issues template updates

modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
=> fix(database): fix sequelize sort

libraries/grpc-sdk/src/interfaces/Model.ts, modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/mongoose-adapter/SchemaConverter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/mongoose-adapter/utils.ts, modules/database/src/adapters/sequelize-adapter/SchemaConverter.ts, modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/utils.ts, modules/database/src/admin/index.ts, modules/database/src/admin/schema.admin.ts
**This PR introduces full index support for MongoDB and PostgreSQL**
There are 3 ways for index definition:
* Define an index in a schema field
* Define an array of indexes in modelOptions of a schema
* Define an array of indexes through new Admin route function
The above are implemented in order to work through the limitations of mongoose (e.g. you can't define a compound index at schema definition) and its differences with sequelize (that's why indexes inside schemas are set in a specific way and then according to db type they are converted in their correct form). 
Example: Definition of index in a schema field
```javascript
loc: {
type: TYPE.Number,
index: {
type: MongoIndexType.GeoSpatial2d,
options: {
name: "locIndex"
}
}
}
```
Example: Definition of an array of indexes in …
=> feat(database,grpc-sdk): index support

libraries/hermes/src/Rest/Rest.ts, libraries/hermes/src/Rest/Swagger.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts
=> fix(hermes, databse): swagger & schema cleanups

modules/database/src/admin/customEndpoints/customEndpoints.admin.ts
=> fix(database): custom endpoints query validation checking wrong access

modules/chat/src/utils/index.ts, modules/database/src/Database.ts, modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts, modules/database/src/controllers/cms/schema.controller.ts, modules/database/src/controllers/cms/utils.ts, modules/database/src/handlers/CustomEndpoints/customEndpoint.handler.ts, modules/database/src/handlers/cms/crud.handler.ts, modules/database/src/handlers/utils.ts, modules/database/src/routes/index.ts
Fixes sorting for CRUD and Custom endpoints.
Multi-field sorting supported.
=> fix(database): cms route sorting

modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/admin/documents.admin.ts
=> fix(database): original schema clean

libraries/grpc-sdk/package.json, libraries/grpc-sdk/src/interfaces/Model.ts
=> fix(grpc-sdk): sequelize type import

modules/database/src/adapters/mongoose-adapter/index.ts
=> fix(database): fix index creation bugs

libraries/grpc-sdk/src/routing/wrapRouterFunctions.ts
=> fix(grpc-sdk): router function wrappers crashes

modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/admin/schema.admin.ts
=> fix(database): check for schema ownership in case of unique index creation

modules/database/src/handlers/CustomEndpoints/customEndpoint.handler.ts
=> fix(database): custom endpoint handler createString length check

libraries/grpc-sdk/package.json, libraries/grpc-sdk/src/index.ts, libraries/grpc-sdk/src/utilities/EventBus.ts, libraries/grpc-sdk/src/utilities/RedisManager.ts, libraries/grpc-sdk/src/utilities/StateManager.ts, packages/commons/src/index.ts, packages/core/src/config-manager/index.ts, packages/core/src/core.proto, yarn.lock
=> Improved redis support

libraries/grpc-sdk/src/routing/interfaces/Route.ts, libraries/grpc-sdk/src/routing/interfaces/types.ts, libraries/grpc-sdk/src/routing/wrapRouterFunctions.ts, libraries/hermes/src/GraphQl/GraphQL.ts, libraries/hermes/src/Rest/util.ts, libraries/hermes/src/cache.utils.ts, libraries/hermes/src/utils/GrpcConverter.ts, modules/router/src/hermes/protoTemplate.ts, packages/admin/src/hermes/protoTemplate.ts
=> feat(grpc-sdk,hermes,admin,router): request params split

docker/get-conduit.sh
This PR re-introduces the oneliner deployment bootstrap script, utilizing Conduit CLI.
It makes use of plain `sh` and generally attempts to be compatible across different shell setups.
Works for Linux and Mac, on both arm64 and amd64, performing the following:
- Installs/updates CLI
- Adds it to the executable $PATH
- Runs: `conduit deploy setup --config`
Once merged, installing CLI and setting up a deployment on Linux/Mac should be as simple as:
`sh <(curl -s https://getconduit.dev/bootstrap)`
**Notes:**
Conduit CLI is currently installed under `~/conduit/bin/conduit`.
~On Linux we should respect Freedesktop XDG standards and use `$HOME/.local/bin` instead.
I'll update this PR addressing the latter.~
Upon further consideration, the above could prove troublesome, as even though the …
=> feat: oneliner deployment setup for Linux and Mac

docker/docker-compose.yml
=> feat: expose docker compose container gRPC ports

libraries/grpc-sdk/src/index.ts
=> fix(grpc-sdk): redis url remap

libraries/grpc-sdk/src/index.ts, libraries/grpc-sdk/src/metrics/MetricsServer.ts, libraries/grpc-sdk/src/metrics/index.ts
Before this prometheus metrics did not include proper labelling of metrics, and default metric aggregation was not working
=> fix(grpc-sdk): Metrics labeling

package.json, yarn.lock
=> build: update lerna to 6.1.0

modules/authentication/src/routes/middleware.ts
Checking if client is undefined or not.
=> fix(authentication): undefined checks

scripts/migrateV10_V15/migrationFiles/migrateV10_V11.js, scripts/migrateV10_V15/migrationFiles/migrateV11_V12.js, scripts/migrateV10_V15/migrationFiles/migrateV12_V13.js, scripts/migrateV10_V15/migrationFiles/schemaCollectionName.js, scripts/migrateV10_V15/migrationFiles/schemaOwnerModule.js
=> fix: v10_15 migrations

libraries/grpc-sdk/src/utilities/Logger.ts
=> feat(grpc-sdk): add namespace label to loki for k8s

scripts/migrateV10_V15/migrationFiles/migrateV12_V13.js
This fixes another issue from the 0.10->0.15 migrations
=> fix: migrations

modules/storage/README.mdx, modules/storage/src/config/config.ts, modules/storage/src/interfaces/StorageConfig.ts, modules/storage/src/providers/aws/index.ts
=> feat(storage): make s3 storage generic with endpoint  fix #497

modules/database/src/adapters/utils/validateSchema.ts
=> fix(database): object comparison failing due to wrong check

modules/database/src/adapters/mongoose-adapter/SchemaConverter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/postgres-adapter/SchemaConverter.ts, modules/database/src/adapters/sequelize-adapter/postgres-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/sql-adapter/SchemaConverter.ts, modules/database/src/adapters/sequelize-adapter/sql-adapter/index.ts, modules/database/src/adapters/utils/index.ts, modules/database/src/adapters/utils/validateFieldChanges.ts, modules/database/src/adapters/utils/validateFieldConstraints.ts
=> fix(database): schema field constraint dependencies, validation

modules/push-notifications/src/handlers/notification-tokens.ts
=> fix(push-notifications): notifications count query being modified

modules/database/src/admin/schema.admin.ts
=> fix(database): admin createSchema() invalid id,createdAt,updatedAt field constraints

libraries/grpc-sdk/src/routing/interfaces/types.ts, libraries/hermes/src/Rest/Rest.ts, modules/authentication/src/handlers/tokenProvider.ts
=> fix(hermes,grpc-sdk,authentication): redirect requests not setting cookies, invalid setCookies format

modules/authorization/src/admin/relations.ts, modules/authorization/src/admin/resources.ts
=> fix(authorization): missing type for delete resource/relation

modules/database/src/adapters/sequelize-adapter/postgres-adapter/PostgresSchema.ts, modules/database/src/adapters/sequelize-adapter/postgres-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/sql-adapter/SQLSchema.ts, modules/database/src/adapters/sequelize-adapter/sql-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/utils/schema.ts, modules/database/src/admin/customEndpoints/customEndpoints.admin.ts, modules/database/src/admin/customEndpoints/utils.ts, modules/database/src/admin/schema.admin.ts, modules/database/src/controllers/customEndpoints/utils.ts, modules/database/src/enums/index.ts, modules/database/src/enums/location.enum.ts, modules/database/src/enums/operation.enum.ts, modules/database/src/handlers/CustomEndpoints/customEndpoint.handler.ts
=> feat(database): duplication and code refactoring

modules/database/src/admin/schema.admin.ts
=> fix(database): admin schema creation adding explicit primaryKey

modules/authorization/src/Authorization.ts, modules/chat/src/Chat.ts, modules/database/src/Database.ts, modules/database/src/controllers/cms/schema.controller.ts, modules/email/src/Email.ts, modules/forms/src/Forms.ts, modules/functions/src/Functions.ts, modules/push-notifications/src/PushNotifications.ts, modules/router/src/Router.ts, modules/storage/src/Storage.ts, packages/admin/src/index.ts
=> refactor: add migrate calls to all schema declarations

libraries/grpc-sdk/src/modules/database/index.ts
=> fix(grpc-sdk): add missing collectionName in getSchema(s) database grpc-sdk wrapper

libraries/grpc-sdk/src/classes/ConduitActiveSchema.ts, modules/authentication/src/admin/team.ts, modules/authentication/src/config/token.config.ts, modules/authentication/src/constants/TokenSchema.ts, modules/authentication/src/constants/index.ts, modules/authentication/src/handlers/oauth2/slack/slack.response.ts, modules/authentication/src/handlers/team.ts, modules/authentication/src/interfaces/IFetchMembersParams.ts, modules/authentication/src/interfaces/index.ts, modules/authentication/src/models/AccessToken.schema.ts, modules/authentication/src/models/RefreshToken.schema.ts, modules/authentication/src/models/User.schema.ts, modules/authentication/src/utils/index.ts, modules/authorization/src/Authorization.ts, modules/chat/src/admin/index.ts, modules/chat/src/models/User.model.ts, modules/chat/src/routes/index.ts, modules/chat/src/utils/index.ts, modules/push-notifications/src/PushNotifications.ts, modules/push-notifications/src/models/User.model.ts, modules/router/src/admin/security.ts
=> Codefactor issues

modules/database/src/adapters/DatabaseAdapter.ts
=> fix(database): wrong legacyCollections comment-out

modules/database/src/admin/customEndpoints/customEndpoints.admin.ts, modules/database/src/admin/documents.admin.ts, modules/database/src/admin/schema.admin.ts, modules/database/src/handlers/utils.ts
=> fix(database): fix sort query param format

modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/sequelize-adapter/sql-adapter/index.ts, modules/database/src/models/DeclaredSchema.schema.ts
feat(database): save extractedSchema to db
fix(database): parentSchema query
refactor(database): add default null value for parent schema
=> refactor(database): storage and handling of embedded schemas for non-pg SQL dbs

modules/database/src/Database.ts, modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts, modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/parser/sql.ts, modules/database/src/adapters/sequelize-adapter/postgres-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/sql-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/utils/schema.ts
=> fix(database): sqlite and general sql recovery issues

modules/database/src/adapters/sequelize-adapter/sql-adapter/SchemaConverter.ts, modules/router/src/models/RouterProxyRoute.schema.ts, packages/admin/src/models/AdminProxyRoute.schema.ts
=> fix(admin, router): proxyRoutes model

libraries/grpc-sdk/src/modules/database/index.ts, modules/authentication/src/admin/user.ts, modules/authentication/src/migrations/UserIdToUserAccessTokenSchemaMigration.ts, modules/authentication/src/migrations/UserIdToUserRefreshTokenSchemaMigration.ts, modules/authentication/src/migrations/UserIdToUserTokenSchemaMigration.ts, modules/authentication/src/migrations/UserIdToUserTwoFactorSchemaMigration.ts, modules/authorization/src/controllers/resource.controller.ts, modules/database/src/Database.ts, modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts, modules/database/src/database.proto, modules/database/src/interfaces/SchemaAdapter.ts
=> feat(database): column existence operation

modules/database/src/adapters/sequelize-adapter/postgres-adapter/SchemaConverter.ts, modules/database/src/adapters/sequelize-adapter/sql-adapter/SchemaConverter.ts
=> fix(database): jsonb sql datatype

modules/database/src/admin/customEndpoints/customEndpoints.admin.ts, modules/database/src/admin/customEndpoints/utils.ts, modules/database/src/admin/index.ts, modules/database/src/admin/schema.admin.ts, modules/database/src/controllers/cms/schema.controller.ts
=> feat(database): import & export for custom schemas & endpoints

modules/database/src/admin/customEndpoints/customEndpoints.admin.ts, modules/database/src/admin/schema.admin.ts
=> fix(database): some fixes for import & export

modules/database/src/admin/schema.admin.ts, modules/database/src/controllers/cms/schema.controller.ts, modules/database/src/utils/utilities.ts
Fix: treat imported/introspected schemas differently in import custom schemas endpoint
=> fix(database): fix import introspected schemas

libraries/hermes/src/GraphQl/GraphQL.ts, libraries/hermes/src/cache.utils.ts
=> fix(hermes): GraphQL not respecting cache header

libraries/hermes/package.json, libraries/hermes/src/GraphQl/utils/cookie.plugin.ts, libraries/hermes/src/Rest/Rest.ts, libraries/hermes/src/index.ts, modules/authentication/src/config/token.config.ts, modules/authentication/src/handlers/tokenProvider.ts, modules/router/package.json, modules/router/src/security/index.ts, packages/admin/package.json, packages/admin/src/index.ts
refactor(hermes,router,admin): move cors middleware to client and admin routers
feat(admin,router): set cors to configured admin/client host
feat(hermes): set cookie domains to host if not provided or empty
=> refactor(hermes,router,admin): proper cors and cookie domains

modules/authentication/src/Authentication.ts
=> fix(authentication): module not removing deprecated config

libraries/grpc-sdk/src/routing/wrapRouterFunctions.ts
feat(grpc-sdk): add router type to logs to distinguish admin/client requests
feat(grpc-sdk): add grpc request metrics per router type
=> feat(grpc-sdk): add router type to logs and separate metrics per type

libraries/hermes/src/GraphQl/utils/cookie.plugin.ts, libraries/hermes/src/Rest/Rest.ts, modules/router/src/config/config.ts, modules/router/src/security/index.ts, packages/admin/src/config/config.ts, packages/admin/src/index.ts
=> refactor(hermes,router,admin): cors settings as config and cookie default domain not set

modules/authentication/src/handlers/team.ts, modules/authentication/src/utils/index.ts, modules/authorization/src/Authorization.ts, modules/authorization/src/authorization.proto, modules/authorization/src/controllers/relations.controller.ts
=> refactor(authentication,authorization):  expand team endpoints and findRelation functionality

modules/authentication/src/admin/team.ts
=> fix(authentication): get team members admin query using wrong query

modules/database/src/adapters/DatabaseAdapter.ts
=> fix(database): add cnd_ prefix check for collectionName

modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/utils/schema.ts, modules/database/src/adapters/utils/validateFieldChanges.ts, modules/database/src/adapters/utils/validateFieldConstraints.ts, modules/database/src/admin/customEndpoints/customEndpoints.admin.ts
=> fix(database): validate extension fields & customEndpoint export output

modules/authentication/src/admin/team.ts, modules/authentication/src/handlers/team.ts, modules/authentication/src/interfaces/IFetchMembersParams.ts, modules/authentication/src/utils/index.ts
feat(authentication): add getTeam endpoint
=> feat(authentication): add populate option in team requests

modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/admin/index.ts, modules/database/src/admin/schema.admin.ts, modules/database/src/utils/SchemaConverter.ts
=> fix(database): fix _id createdAt updatedAt format

modules/authentication/src/handlers/team.ts, modules/authentication/src/utils/index.ts, modules/database/src/handlers/CustomEndpoints/customEndpoint.handler.ts
fix(database): custom endpoint creation issue with residual commas
fix(authentication): missing middleware in team role modification
feat(authentication): add role field when fetching team members
=> fix(database,authentication): customEndpoints and missing middleware

modules/database/src/adapters/DatabaseAdapter.ts
=> fix(database): add modelOptions timestamps

libraries/grpc-sdk/src/routing/wrapRouterFunctions.ts, modules/email/src/models/EmailTemplate.schema.ts
fix(grpc-sdk): result parsing when plain string
fix(email): template model not having subject as required
=> fix(grpc-sdk,email): result parsing & template model subject requirement

modules/storage/src/handlers/file.ts
=> fix(storage): correction of check in validation 

modules/authentication/src/config/teams.config.ts, modules/authentication/src/handlers/team.ts
=> refactor(authentication): add allowEmailMismatchForInvites feature

modules/database/src/admin/customEndpoints/customEndpoints.admin.ts
=> fix(database): exportCustomEndpoints() returning schema ids

modules/authentication/src/handlers/common.ts, modules/authentication/src/routes/middleware.ts
=> feat(authentication): add cleanup code to delete expired refresh/access tokens

modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/postgres-adapter/PgSchemaConverter.ts, modules/database/src/adapters/sequelize-adapter/sql-adapter/SqlSchemaConverter.ts, modules/database/src/introspection/sequelize/utils.ts
=> fix(database): use correct schema converter per dialect

libraries/module-tools/package.json, yarn.lock
=> chore(module-tools): upgrade packages

modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
fix(database): populating parentDoc in findByIdAndUpdate without it being needed
=> feat(database): allow populate when population field is in association

modules/authentication/src/handlers/tokenProvider.ts
=> fix(authentication): tokens set with wrong expiry on  JWT and Cookies

libraries/grpc-sdk/src/modules/authentication/index.ts, libraries/module-tools/src/helpers/GrpcToParsedRouterRequest.ts, libraries/module-tools/src/helpers/index.ts, modules/authentication/src/Authentication.ts, modules/authentication/src/authentication.proto, modules/storage/src/Storage.ts, modules/storage/src/adapter/StorageParamAdapter.ts
=> feat(authentication,storage,module-tools,grpc-sdk): teamDelete rpc & grpcToParsedRouterRequest helper

modules/authorization/src/controllers/permissions.controller.ts, modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts, modules/database/src/adapters/sequelize-adapter/index.ts
This implementation has been tested only for postgres. We need to change the view names, as adding ':' results in a Syntax Error.
=> feat(database): add views for sql

libraries/grpc-sdk/src/modules/database/index.ts, modules/authorization/src/controllers/permissions.controller.ts, modules/authorization/src/utils/index.ts, modules/database/src/Database.ts, modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/SchemaAdapter.ts, modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts, modules/database/src/adapters/sequelize-adapter/index.ts, modules/database/src/admin/schema.admin.ts, modules/database/src/database.proto, modules/database/src/interfaces/View.ts, modules/database/src/interfaces/index.ts, modules/database/src/models/Views.schema.ts, modules/database/src/models/index.ts
TODO:
- ~~Parse the result of getAuthorizedQuery() for functions that return many results as $in doesn't work in sequelize~~
- ~~Drop views that are associated with tables that migrate~~
- ~~Correct syntax errors in mysql create view query~~
=> feat(database): sql views support

modules/database/src/adapters/SchemaAdapter.ts
=> fix(database): correct typos

modules/authentication/src/handlers/phone.ts, modules/sms/src/providers/awsSns.ts, modules/sms/src/providers/clickSend.ts
=> fix(authentication,sms): hash sms phone numbers & fix bugs in authenticate()

modules/authentication/src/handlers/magicLink.ts
=> fix(authentication): magic link hook verificationToken url param

modules/authentication/src/Authentication.ts, modules/authentication/src/handlers/local.ts, modules/authentication/src/handlers/magicLink.ts
This PR resolves the following additional query issues around case-sensitive email addresses:
- forgotPassword (Client API)
- magicLink (Client API)
- changePass (gRPC API)
=> fix(authentication): case-sensitive User.email queries

modules/authentication/src/handlers/common.ts, modules/authentication/src/handlers/tokenProvider.ts, modules/authentication/src/models/RefreshToken.schema.ts
=> fix(authentication): refresh tokens not being deleted on logout

modules/authentication/src/handlers/magicLink.ts
This should allow customized MagicLink templates to incorporate User details.
=> feat(authentication): pass User object to MagicLink email template

modules/database/src/adapters/sequelize-adapter/parser/index.ts
=> fix(database): excluded fields ignored when not using select

libraries/grpc-sdk/src/index.ts, libraries/module-tools/src/ManagedModule.ts, libraries/module-tools/src/classes/ConduitServiceModule.ts, libraries/module-tools/src/interfaces/ModuleLifecycleStage.ts, modules/authorization/src/router/index.ts, packages/core/src/config-manager/service-discovery/index.ts, yarn.lock
fix(authorization): route registration was happening before router available
feat(module-tools): lifecycle stage tracking to better coordinate actions
feat(module-tools): registration status boolean to block health updates until module registered
feat(grpc-sdk): updateModuleHealth function for core
refactor(grpc-sdk): re-write waitForExistence to use events, to improve performance and accuracy
After a lot of digging, I found various inconsistencies in module lifecycle. This PR addresses them, and also improves performance (at least on startup) by removing greedy sleep calls and replacing with the events
If adding a **new feature**, the PR's description …
=> refactor(grpc-sdk,module-tools): service discovery lifecycle to improve reliability

libraries/grpc-sdk/src/modules/authentication/index.ts, modules/authentication/src/Authentication.ts, modules/authentication/src/authentication.proto
=> feat(authentication,grpc-sdk): getTeam, createTeam gRPC methods

modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/admin/customEndpoints/customEndpoints.admin.ts
=> fix(database): Mongoose types

libraries/grpc-sdk/src/modules/storage/index.ts, modules/storage/src/Storage.ts, modules/storage/src/storage.proto
=> refactor(storage): add extra rpc params for authz

modules/authorization/src/controllers/cache.controller.ts, modules/authorization/src/utils/index.ts
=> fix(authorization): Postgres access list query

modules/database/src/adapters/SchemaAdapter.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
=> fix(database): sql findMany authorized pagination

libraries/hermes/src/GraphQl/GraphQlParser.ts
=> fix(hermes): GraphQL parser constructResolver() unpopulated relation field formatting

modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
=> fix(database): SQL findByIdAndReplace() setting _id, createdAt to undefined

libraries/grpc-sdk/src/modules/authorization/index.ts, modules/authorization/src/Authorization.ts, modules/authorization/src/admin/relations.ts, modules/authorization/src/authorization.proto, modules/authorization/src/controllers/index.controller.ts, modules/authorization/src/controllers/relations.controller.ts, modules/database/src/adapters/SchemaAdapter.ts
=> feat(authorization, database):  createRelations()

modules/database/src/adapters/sequelize-adapter/index.ts
This PR provides a workaround for concurrent `createView()` operations resulting in unique violation errors.
This issue only seems to be affecting the SQL adapter.
Initially investigated by @Renc17.
=> fix(database): SQL createView() already exists race condition

modules/authentication/src/handlers/biometric.ts, modules/authentication/src/models/index.ts
=> fix(authentication): biometrics issues

libraries/grpc-sdk/src/index.ts
=> fix(grpc-sdk): REDIS_PASSWORD env setting Redis username

modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/controllers/cms/schema.controller.ts
=> fix(database): delete permissions

libraries/hermes/src/Socket/Socket.ts, modules/router/src/security/index.ts
refactor(hermes): use io engine for express middleware compat
fix(router): disable rate limiter for sockets due to IP not being available
=> fix(router): disable rate limiter for sockets due to IP not being available

modules/authorization/src/controllers/index.controller.ts, modules/authorization/src/controllers/permissions.controller.ts, modules/authorization/src/controllers/relations.controller.ts, modules/authorization/src/controllers/resource.controller.ts, modules/authorization/src/models/ActorIndex.schema.ts, modules/authorization/src/models/ObjectIndex.schema.ts, modules/authorization/src/models/Permission.schema.ts, modules/authorization/src/models/Relationship.schema.ts, modules/authorization/src/utils/index.ts, modules/database/src/adapters/utils/database-transform-utils.ts
=> refactor(authorization): further split fields

libraries/grpc-sdk/src/types/db.ts, modules/authorization/src/migrations/actorIndex.migration.ts, modules/authorization/src/migrations/index.ts, modules/authorization/src/migrations/objectIndex.migration.ts, modules/authorization/src/migrations/permission.migration.ts, modules/authorization/src/migrations/relationship.migration.ts, modules/chat/src/config/config.ts, modules/chat/src/migrations/chatMessage.migrate.ts, modules/chat/src/migrations/chatRoom.migrate.ts, modules/chat/src/migrations/index.ts, modules/chat/src/models/ChatRoom.schema.ts, modules/chat/src/models/Message.schema.ts, modules/chat/src/routes/index.ts
=> feat(chat): introduce auditMode, room deletions on leave and remove unique name requirement from rooms

modules/database/src/handlers/CustomEndpoints/utils.ts
=> fix(database): custom endpoint date casting conflict with mongoose casts

modules/authentication/src/admin/index.ts
This PR fixes a bug where `Authentication` module's `Team`-related admin endpoints would register unconditionally, regardless of whether `Authorization` was available.
This changes so that the relevant endpoints are only registered once Authz becomes available.
=> fix(authentication): unconditional team admin endpoint registration

modules/router/src/security/handlers/rate-limiter/index.ts
=> refactor(router): do not count OPTIONS requests towards request limit

modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/admin/index.ts, modules/database/src/admin/schema.admin.ts
Import/export endpoints now allow the importing/exporting of conduit schemas' extensions
Also, this PR fixes a bug in extension setting
=> feat(database): add import/export extensions logic to existing endpoints

modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
=> fix(database): findOne() null query filters

modules/database/src/adapters/SchemaAdapter.ts, modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts, modules/database/src/adapters/sequelize-adapter/utils/pathUtils.ts, modules/database/src/adapters/sequelize-adapter/utils/schema.ts, modules/database/src/controllers/cms/schema.controller.ts
=> fix(database): query types, Authz check condition cleanups

libraries/grpc-sdk/package.json, libraries/grpc-sdk/src/utilities/StateManager.ts, libraries/module-tools/src/utilities/linearBackoffTimeout.ts, packages/admin/src/index.ts, packages/core/src/config-manager/admin/routes/GetModules.route.ts, packages/core/src/config-manager/admin/routes/GetMonoConfig.route.ts, packages/core/src/config-manager/config-storage/index.ts, packages/core/src/config-manager/index.ts, packages/core/src/config-manager/service-discovery/ServiceMonitor.ts, packages/core/src/config-manager/service-discovery/ServiceRegistry.ts, packages/core/src/config-manager/service-discovery/index.ts, yarn.lock
This PR attempts to fix SD inconsistencies, with modules being advertised as unhealthy or not even registered when they are online. It might need a couple more changes to make sure, but initial testing seems to show that the issues are resolved.
Currently includes several logs to assist with testing. Should remove before merging.
=> refactor(core): service discovery mechanism

modules/authorization/src/Authorization.ts, modules/authorization/src/controllers/index.controller.ts, modules/authorization/src/controllers/permissions.controller.ts, modules/authorization/src/controllers/queue.controller.ts, modules/authorization/src/controllers/relations.controller.ts
=> refactor(authorization): index controller use singleton pattern

modules/authorization/src/utils/index.ts
=> fix(authorization): createView() sql queries failing due to unpreserved camel case column names

libraries/module-tools/src/routing/wrapRouterFunctions.ts
=> fix(module-tools): unexpected/unhandled errors parse human readable message

modules/email/src/config/config.ts, modules/email/src/email-provider/index.ts
=> refactor(email): remove domain config from mailgun & use sendingDomain

modules/authorization/src/controllers/queue.controller.ts, modules/authorization/src/jobs/constructRelationIndex.ts
=> fix(authorization): index building jobs initialized grpc-sdk incorrectly

libraries/grpc-sdk/src/classes/ConduitModule.ts, libraries/grpc-sdk/src/classes/HealthCheck.ts, packages/core/src/config-manager/service-discovery/index.ts
fix(grpc-sdk): middlewares not injected in module clients
refactor(core): error logging in module recovery
=> fix(grpc-sdk): health check middleware injection

modules/push-notifications/src/providers/Firebase.provider.ts
=> refactor(push-notifications): add return statement on update provider

libraries/grpc-sdk/src/modules/authentication/index.ts, modules/authentication/src/Authentication.ts, modules/authentication/src/authentication.proto
=> feat(authentication): Add/RemoveTeamMembers gRPC rpcs

modules/database/src/adapters/mongoose-adapter/index.ts
This PR follows the same logic as #688 
=> fix(database): add catch to mongoose-adapter createView()

modules/database/src/admin/customEndpoints/utils.ts
=> fix(database): group field custom endpoints query bug

modules/authentication/src/Authentication.ts
=> fix(authentication): add/removeTeamMember rpc field mapping

libraries/grpc-sdk/src/utilities/EventBus.ts, libraries/grpc-sdk/src/utilities/StateManager.ts
=> fix(grpc-sdk): Redis connections not closing on process exit

modules/authorization/src/jobs/constructRelationIndex.ts
=> fix(authorization): constructRelationIndex not reusing grpc-sdk

modules/router/src/Router.ts, packages/admin/src/index.ts
Currently, when database restarted, especially in cloud environments, it was trying to register client/admin routes, but due to the patch middlewares operation which requires database availability this was sometimes failing. This was caused due to the modules not having an updated database connection and were trying to communicate with a database instance that no longer existed.
=> fix(router,admin): register route crashing between database restarts, due to clients not having updated connections

modules/database/src/Database.ts, modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/SchemaAdapter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts
=> fix(database): views not being shared between instances

modules/authorization/src/Authorization.ts, modules/authorization/src/admin/index.ts, modules/authorization/src/controllers/index.controller.ts, modules/authorization/src/controllers/queue.controller.ts, modules/authorization/src/jobs/constructRelationIndex.ts, modules/authorization/src/jobs/processPossibleConnections.ts
refactor(authorization): remove queue waitForIdle on re-indexing to avoid loop blocks
refactor(authorization): decrease job concurrency to avoid memory and cpu bottlenecks
=> refactor(authorization): performance improvements on background jobs/re-indexing

.github/workflows/standalone.build.yaml, .github/workflows/standalone.production.yaml, docker/docker-compose.standalone.yml, standalone.Dockerfile, standalone/ecosystem.config.js
=> feat: standalone docker image

modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts, modules/database/src/adapters/mongoose-adapter/index.ts
=> fix(database): mongoose parseStringToQuery EJSON -> JSON

modules/database/src/adapters/DatabaseAdapter.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/index.ts
=> fix(database): execRawQuery check if collection exists in views

modules/push-notifications/src/providers/Firebase.provider.ts, modules/push-notifications/src/providers/OneSignal.provider.ts
refactor(push-notifications): cleanup imports for firebase and onesignal
=> refactor(push-notifications): remove dual initialization of firebase

modules/authentication/src/handlers/common.ts, modules/authentication/src/handlers/tokenProvider.ts, modules/authentication/src/routes/middleware.ts
… all the way
refactor(authentication): convert token provider operations to use utc all the way
refactor(authentication): remove expiration check in payload since it's covered by jwt library
refactor(authentication): change date comparisons to use utc and clear up error messages
=> refactor(authentication): use utc consistently in tokens & rework some error cases

modules/authorization/src/authorization.proto
This PR reverts `CreateResourceAccessList` RPC's field ordering cleanup from #955, re-establishing compatibility with existing `grpc-sdk` builds.
=> fix(authorization): createResourceAccessList API breakage

modules/authentication/src/handlers/team.ts
=> feat(authentication): endpoint to update team name

modules/push-notifications/src/providers/Firebase.provider.ts, modules/push-notifications/src/providers/base.provider.ts
fix(push-notifications): firebase notifications crash due to expired tokens
=> refactor(push-notifications): send notification always fetch all user tokens for specified platform

modules/authentication/src/config/apple.config.ts, modules/authentication/src/config/bitbucket.config.ts, modules/authentication/src/config/facebook.config.ts, modules/authentication/src/config/figma.config.ts, modules/authentication/src/config/github.config.ts, modules/authentication/src/config/gitlab.config.ts, modules/authentication/src/config/google.config.ts, modules/authentication/src/config/linkedIn.config.ts, modules/authentication/src/config/microsoft.config.ts, modules/authentication/src/config/reddit.config.ts, modules/authentication/src/config/slack.config.ts, modules/authentication/src/config/twitch.config.ts, modules/authentication/src/config/twitter.config.ts, modules/authentication/src/constants/Oauth2.default.schema.ts, modules/authentication/src/handlers/local.ts, modules/authentication/src/handlers/oauth2/OAuth2.ts, modules/authentication/src/handlers/phone.ts, modules/authentication/src/handlers/team.ts
Also:
- move accountLinking option to the config of all providers
- remove verification requirement for forgot password emails
=> feat(authentication): validate team invites before user creation for all authentication methods

modules/chat/src/admin/index.ts
=> fix(chat): createRoom admin API participants validation

modules/push-notifications/src/PushNotifications.ts
This PR fixes some bugs found in the health update logic of the Push Notifications module
=> fix(push-notifications): pushNotifications health updates

libraries/grpc-sdk/src/modules/storage/index.ts, modules/storage/src/Storage.ts, modules/storage/src/storage.proto
=> feat(storage): introduce gRPC call to get a file's URL

modules/router/package.json, modules/router/src/security/handlers/rate-limiter/index.ts, modules/router/src/security/index.ts, yarn.lock
This aims to fix random 429 issues that seem to be associated with the library implementation.
=> refactor(router): remove rate limit library and add custom implementation

modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts, modules/database/src/adapters/mongoose-adapter/index.ts, modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts, modules/database/src/adapters/sequelize-adapter/index.ts
This PR fixes some bugs found in database views and allows view overwriting
=> fix(database): view fixes

modules/push-notifications/src/providers/OneSignal.provider.ts
This PR adds missing deletion of expired push notification tokens for one-signal provider
=> fix(push-notifications): delete expired tokens for one-signal provider

libraries/grpc-sdk/package.json, libraries/grpc-sdk/rollup.config.js, libraries/grpc-sdk/src/index.ts, libraries/grpc-sdk/src/utilities/RedisManager.ts, libraries/grpc-sdk/tsconfig.json, libraries/hermes/package.json, libraries/module-tools/package.json, libraries/module-tools/rollup.config.js, libraries/module-tools/src/ManagedModule.ts, libraries/module-tools/src/classes/ConduitServiceModule.ts, libraries/module-tools/tsconfig.json, modules/authorization/src/Authorization.ts, modules/chat/src/Chat.ts, modules/email/src/Email.ts, modules/forms/src/Forms.ts, modules/functions/src/Functions.ts, modules/push-notifications/src/PushNotifications.ts, modules/router/src/Router.ts, modules/storage/src/Storage.ts, packages/core/src/config-manager/index.ts, yarn.lock
This PR introduces support for commonjs projects that was broken in 0.16.0 rc releases when we moved the entire platform to ESM. This introduces no breaking changes into the project, BUT update of both grpc-sdk and module-tools is required. Running different versions will potentially cause issues.
=> feat(grpc-sdk,module-tools): support commonjs projects

modules/authentication/src/handlers/team.ts
- [] A convincing reason for adding this feature 
=> feat(authentication): allow setting redirectUri for invites

modules/storage/src/admin/index.ts
=> fix(storage): getFolders by parent/root/all scope

libraries/grpc-sdk/src/modules/authentication/index.ts, modules/authentication/src/Authentication.ts, modules/authentication/src/admin/index.ts, modules/authentication/src/admin/user.ts, modules/authentication/src/authentication.proto, modules/authentication/src/config/config.ts, modules/authentication/src/handlers/local.ts, modules/authentication/src/handlers/magicLink.ts, modules/authentication/src/handlers/oauth2/OAuth2.ts, modules/authentication/src/handlers/oauth2/apple/apple.ts, modules/authentication/src/handlers/oauth2/facebook/facebook.ts, modules/authentication/src/handlers/oauth2/google/google.ts, modules/authentication/src/handlers/oauth2/interfaces/RedirectOptions.ts, modules/authentication/src/handlers/phone.ts, modules/authentication/src/handlers/team.ts, modules/authentication/src/handlers/twoFa.ts, modules/authentication/src/models/User.schema.ts, modules/authentication/src/routes/index.ts, modules/authentication/src/routes/middleware.ts
This PR introduces a new authentication feature: **Anonymous users**
Anonymous users are created without credentials, but granted with access tokens and limited access to auth endpoints
Whenever the anonymous user decides to register, the same user doc is updated with given credentials and any other associated data
=> feat(authentication, grpc-sdk): anonymous users

modules/storage/src/admin/index.ts
This PR implements a minor fix to update the file search field following the addition of the alias field to the file schema.
=> fix(storage): search files alias integration

modules/authorization/src/admin/index.ts, modules/authorization/src/controllers/queue.controller.ts
Also rename job logs to better show completed operations
=> feat(authorization): add "soft" param to trigger re-indexing without index wipe

modules/authentication/src/Authentication.ts
=> fix(authentication): type bug

modules/chat/src/Chat.ts, modules/chat/src/admin/index.ts, modules/chat/src/models/ChatParticipantsLog.schema.ts, modules/chat/src/routes/InvitationRoutes.ts, modules/chat/src/routes/index.ts, modules/chat/src/utils/index.ts
=> refactor(chat)!: admin/router missing endpoints/query params/participants actions

modules/authentication/src/utils/index.ts, modules/authorization/src/controllers/relations.controller.ts
=> fix(authentication, authorization): teamMembers count, remove default pagination from rpc routes

libraries/grpc-sdk/src/classes/ConduitModule.ts, libraries/hermes/src/utils/GrpcConverter.ts, modules/authentication/src/utils/index.ts, modules/authorization/src/controllers/relations.controller.ts, modules/router/src/Router.ts, packages/admin/src/index.ts, packages/core/src/config-manager/service-discovery/index.ts
=> refactor: introduce grpc client params to enable LB, fix state storing inconsistencies. 

.gitignore, modules/database/src/permissions/index.ts
=> fix(database): canModify extensions remove redundant nested fields check, parse mongo nested update syntax

modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts
=> fix(database): wrong query in mongoose findOne

modules/authentication/src/handlers/local.ts
This PR introduces a default behavior for registration with an invitation token. User data from the token is automatically added to the user record during registration. If any predefined user data needs to be modified, the userData parameter can overwrite the relevant fields.
=> feat(authentication): default behaviour on register with invitation token

modules/authentication/src/handlers/local.ts
=> fix(authentication): merge fallback empty objects

modules/authentication/src/Authentication.ts, modules/authentication/src/authentication.proto
=> feat(authentication): user activate/deactivate gRPC routes

modules/authentication/src/handlers/team.ts
=> feat(authentication): return email in getInvitationTokenUserData

modules/router/src/security/handlers/captcha-validation/index.ts
=> fix(router): google recaptcha verification url is incorrect

modules/functions/src/admin/index.ts, modules/functions/src/controllers/utils.ts, modules/functions/src/interfaces/IWebInputs.interface.ts, modules/functions/src/models/FunctionExecutions.schema.ts
=> fix(functions): pagination/execution relation/invalid params

modules/authentication/src/config/local.config.ts, modules/authentication/src/utils/index.ts
=> feat(authentication): make resend verification threshold configurable

libraries/grpc-sdk/build.sh, libraries/grpc-sdk/src/classes/ConduitAuthorizedResource.ts, libraries/grpc-sdk/src/classes/ConduitModule.ts, libraries/grpc-sdk/src/classes/HealthCheck.ts, libraries/grpc-sdk/src/index.ts, libraries/grpc-sdk/src/modules/admin/index.ts, libraries/grpc-sdk/src/modules/authentication/index.ts, libraries/grpc-sdk/src/modules/authorization/index.ts, libraries/grpc-sdk/src/modules/config/index.ts, libraries/grpc-sdk/src/modules/pushNotifications/index.ts, libraries/module-tools/src/ManagedModule.ts, libraries/module-tools/src/classes/ConduitServiceModule.ts, modules/authentication/src/Authentication.ts, modules/authentication/src/authentication.proto, modules/authentication/src/interfaces/IFetchMembersParams.ts, modules/authorization/src/Authorization.ts, modules/authorization/src/authorization.proto, modules/chat/src/chat.proto, modules/database/src/Database.ts, modules/database/src/database.proto, modules/router/src/router.proto, packages/core/src/config-manager/service-discovery/ServiceMonitor.ts, packages/core/src/core.proto
=> fix: ts-proto messagefns export bug

modules/database/src/adapters/mongoose-adapter/index.ts
=> fix(database): create index type

modules/authentication/src/handlers/local.ts
=> fix(authentication): verify email with code wrongfully tries to redirect

libraries/hermes/src/Rest/Rest.ts, libraries/hermes/src/Rest/Swagger.ts, libraries/hermes/src/Rest/SwaggerParser.ts
chore(hermes): change get to use for scalar requests
=> fix(hermes): swagger ID type causing issues with testing

modules/router/src/security/handlers/rate-limiter/index.ts
=> refactor(router): change header IP read to reduce false-positives

modules/authentication/Dockerfile, modules/authorization/Dockerfile, modules/chat/Dockerfile, modules/database/Dockerfile, modules/email/Dockerfile, modules/forms/Dockerfile, modules/functions/Dockerfile, modules/push-notifications/Dockerfile, modules/router/Dockerfile, modules/sms/Dockerfile, modules/storage/Dockerfile, packages/Dockerfile
fix: include missing NODE_ENV
fix: replace yarn start command with pure node to reduce memory consumption
=> fix: minor issues with dockerfiles causing reduced performance

modules/database/src/controllers/cms/utils.ts, modules/database/src/controllers/customEndpoints/utils.ts
=> fix(database): add visibility for populate query param

libraries/grpc-sdk/src/modules/email/index.ts, modules/email/src/Email.ts, modules/email/src/admin/index.ts, modules/email/src/email.proto, modules/email/src/interfaces/UpdateTemplateParams.ts, modules/email/src/interfaces/index.ts, modules/email/src/services/email.service.ts
Fixes:
- sender body param not set
- declared endpoint return type was not matching with endpoint's actual return data
=> feat(email): updateTemplate grpc

modules/database/src/controllers/customEndpoints/utils.ts, modules/database/src/interfaces/CustomEndpoint.ts, modules/database/src/models/CustomEndpoints.schema.ts
=> feat(database): support description in custom endpoints

libraries/module-tools/src/routing/wrapRouterFunctions.ts
=> feat(module-tools): introduce status mapping in logs to provide more information

docker/docker-compose.yml, libraries/hermes/src/index.ts, libraries/hermes/src/metrics/RouteTrie.ts, libraries/hermes/src/metrics/middleware.ts, libraries/module-tools/src/metrics/index.ts
=> feat(module-tools,router):  introduce http metrics

modules/authentication/src/handlers/team.ts
=> feat(authentication): delete duplicate team invitation

libraries/grpc-sdk/src/modules/authentication/index.ts, modules/authentication/src/Authentication.ts, modules/authentication/src/authentication.proto
=> feat(authentication): delete invitation RPC

modules/authentication/src/handlers/team.ts
=> fix(authentication): wrong variable in TeamInvite email

modules/email/src/Email.ts, modules/email/src/admin/index.ts, modules/email/src/email.proto, modules/email/src/interfaces/RegisterTemplateParams.ts, modules/email/src/models/EmailTemplate.schema.ts, modules/email/src/services/email.service.ts
=> feat(email): port email json template from v-next branch

libraries/grpc-sdk/src/classes/ConduitModule.ts, libraries/hermes/src/utils/GrpcConverter.ts, libraries/module-tools/src/classes/ConduitServiceModule.ts, libraries/module-tools/src/classes/GrpcServer.ts, libraries/module-tools/src/helpers/wrapGrpcFunctions.ts
refactor(grpc-sdk,hermes): grpc options change to support HA in k8s clusters
refactor(module-tools): noAuth to addService of GrpcServer to exclude services from authentication
=> refactor(grpc-sdk,hermes,module-tools): Extra options added so that on k8s and multi-instance cases load balancing works on grpc-side
