ConduitPlatform/Conduit

- modules/cms/src/admin/admin.ts
- modules/cms/src/admin/schema.admin.ts
CMS.getSchema and CMS.getSchemas now also return schemas not-owned by CMS.
CustomEndpoints remains blacklisted and therefore won't show up.
This PR also drops getSchemasFromOtherModules route as it's now pointless and unused in production, therefore branding as Breaking Change and deprecating straight away to avoid cluttering up the codebase.
@KostasFeg I believe Conduit-UI makes use of it to some extent?
BREAKING CHANGE:
Removed CMS.getSchemasFromOtherModules (GET: /admin/cms/schemasFromOtherModules)
If adding a **new feature**, the PR's …
> feat(cms): remove cms-only filtering from getSchema, getSchemas

- modules/cms/src/admin/admin.ts
- modules/cms/src/admin/schema.admin.ts
Schemas may now be filtered based on multiple valid owner names.
CMS.getSchemas's owner query param now accepts an array of strings (previously a string containing a single module name).
CMS.getSchema's owner query param got dropped.
This is not a breaking change as said params were only introduced in master (not branched into a release).
Adding a route returning all the module names that currently own schemas was required for filtering on Conduit-UI as existing module getters only list modules currently online and don't filter out modules with no schemas. 
**What kind of change does this PR introduce?**
If …
> CMS getSchemas ownerModule array filter, getSchemaOwners route

- libraries/grpc-sdk/src/helpers/RoutingUtilities.ts
Example: 'PostLogin' wouldn't register after 'PostLoginNew'
> fix(grpc-sdk): route rpc strings not generated for function names comprised of registered subsets

- modules/storage/src/handlers/file.ts
Fixes updateFile saving File.name as undefined on requests where name param is not provided.
Fixes folder names requiring a slash suffix (pain-free workraound).
> fix(storage): updateFile handler storing undefined filename when no name param provided and folder param workaround

- modules/database/src/Database.ts
- modules/database/src/index.ts
- packages/admin/src/middleware/Admin.middleware.ts
Converted env vars names to macro case.
DB_TYPE for PostgreSQL is now 'postgres' (previously 'sql').
This is **not** a breaking change.
Backwards compatibility has been preserved.
Database:
- databaseType (mongodb/sql) -> DB_TYPE (mongodb/postgres)
- databaseUrl -> DB_URL
Admin:
- masterkey -> MASTER_KEY
Updated env var names based on macro case convention.
> chore(database,admin): convert env var names to macro case, update PostgreSQL db type value

- packages/admin/src/index.ts
- packages/admin/src/middleware/Auth.middleware.ts
- packages/router/src/controllers/Rest/Rest.ts
- packages/router/src/controllers/Rest/Swagger.ts
- packages/router/src/controllers/Routing.ts
Closes #80 and generally improves Swagger route doc generation.
- Admin routes are now properly prefixed by `/admin/` so that Swagger users no longer need to guess the proper baseUrl.
- Admin routes now require proper admin headers.
This PR also converts Admin router's `Authentication` header format from `JWT adminToken` to `Bearer adminToken`.
This change improves compatibility with OpenAPI and Swagger, while also improving consistency with user authentication.
This bit is not a breaking change as backwards compatibility has been preserved.
> fix(router, admin): Admin Swagger headers and route paths

- packages/router/src/controllers/GraphQl/GraphQL.ts
- packages/router/src/controllers/Rest/Rest.ts
- packages/router/src/controllers/Router.ts
- packages/router/src/controllers/Socket/Socket.ts
**What kind of change does this PR introduce?**
Fixes #89.
> fix(router): excessive REST router refreshes

- libraries/grpc-sdk/src/classes/ConduitModule.ts
- libraries/grpc-sdk/src/index.ts
- libraries/grpc-sdk/src/interceptors/index.ts
- libraries/grpc-sdk/src/interceptors/moduleName.ts
- libraries/grpc-sdk/src/modules/admin/index.ts
- libraries/grpc-sdk/src/modules/authentication/index.ts
- libraries/grpc-sdk/src/modules/chat/index.ts
- libraries/grpc-sdk/src/modules/cms/index.ts
- libraries/grpc-sdk/src/modules/config/index.ts
- libraries/grpc-sdk/src/modules/databaseProvider/index.ts
- libraries/grpc-sdk/src/modules/email/index.ts
- libraries/grpc-sdk/src/modules/forms/index.ts
- libraries/grpc-sdk/src/modules/payments/index.ts
- libraries/grpc-sdk/src/modules/pushNotifications/index.ts
- libraries/grpc-sdk/src/modules/router/index.ts
- libraries/grpc-sdk/src/modules/sms/index.ts
- libraries/grpc-sdk/src/modules/storage/index.ts
- packages/router/src/controllers/Socket/Socket.ts
- packages/router/src/index.ts
- packages/router/src/models/SocketPush.model.ts
Backport of #82 for v0.10.
This also backports 'module-name' being passed as gRPC call metadata due to the socket fix depending on it.
> v0.10 backport sockets

- docker/Makefile
Bumped backend container tags to v0.12.4.
Container Makefile update.
> chore: bump Makefile backend tag (v0.12.4)

- modules/authentication/src/routes/routes.ts
Google handlers were getting re-validated in place of Github handlers.
Way more importantly, this fixes Authentication not registering certain routes on initial config request (eg local auth login after setting username identifier)!
> fix(authentication): googleHandlers being validated in place of githubHandlers

- modules/authentication/src/routes/routes.ts
Backport of #101 for v0.11.
Google handlers were getting re-validated in place of Github handlers.
Way more importantly, this fixes Authentication not registering certain routes on initial config request (eg local auth login after setting username identifier)!
> fix(authentication): googleHandlers being validated in place of githubHandlers (backport #101)

- packages/router/src/controllers/Socket/Socket.ts
Fixes socket emits for specified rooms not behaving as expected.
Previously, we'd have every socket in target namespace emitting events received by every **other** socket in the specified room/s.
This results in multiple unexpected side-effects, where single socket connections never receive data (as there's no other socket to forward it to them), connections of 3+ sockets possibly resulting in data being emitted multiple times from different sockets etc.
This change effectively makes it so that:
1. Every socket push successfully sends data to every single socket that:
- is connected in the same `namespace`
- is listening on the particular `event`
- has joined the socket `room` the data is intended for
2. Data generated through gRPC (eg `Chat.sendMessage`) reaches every socket matching the …
> fix(router): socket emits with specified receivers misbehaving

- packages/router/src/controllers/Socket/Socket.ts
Backport of #109 for v10.
Socket behavior was retested before and after backport.
> fix(router): socket emits with specified receivers misbehaving (backport #109)

- docker/Makefile
- docker/get-conduit.sh
Bumped Conduit version to 0.12.5.
Bumped Conduit UI version to 0.12.1.
Fixed UI container missing `MASTER_KEY` env var (issue ever since master key fix in 0.12.4).
Added an `update` target to conveniently replace the `Makefile` with the latest version available without the users actively looking it up.
Most likely fixed a string comparison check in `start-database`.
Makefile related updates, fixes, additions.
> Makefile fixes and updates (v0.12.5)

- libraries/grpc-sdk/src/helpers/RoutingUtilities.ts
- libraries/grpc-sdk/src/helpers/wrapRouterFunctions.ts
- libraries/grpc-sdk/src/types/index.ts
- modules/authentication/src/config/config.ts
- modules/authentication/src/handlers/AuthenticationProviders/OAuth2.ts
- modules/authentication/src/handlers/common.ts
- modules/authentication/src/handlers/facebook/facebook.ts
- modules/authentication/src/handlers/figma/figma.ts
- modules/authentication/src/handlers/github/github.ts
- modules/authentication/src/handlers/google/google.ts
- modules/authentication/src/handlers/local.ts
- modules/authentication/src/handlers/microsoft/microsoft.ts
- modules/authentication/src/handlers/phone.ts
- modules/authentication/src/handlers/service.ts
- modules/authentication/src/handlers/slack/slack.ts
- modules/authentication/src/handlers/twitch/twitch.ts
- modules/authentication/src/interfaces/Cookie.ts
- modules/authentication/src/routes/routes.ts
- modules/authentication/src/utils/auth.ts
- packages/router/src/controllers/GraphQl/GraphQL.ts
- packages/router/src/controllers/GraphQl/utils/cookie.plugin.ts
- packages/router/src/controllers/Rest/Rest.ts
- packages/router/src/controllers/Rest/util.ts
Many applications use cookies for their authentication tokens, and conduit should have an option to set cookies instead of providing creds in response.
- Cookie functionality is configurable through `setCookies.enabled` config option.
- When cookies are returned from authentication module, router wraps them in the response object.
- When a request arrives, cookies are accessible through `call.request.context.cookies` object.
> Cookies #23dq8hb

- packages/admin/src/index.ts
- packages/commons/src/index.ts
- packages/commons/src/modules/Admin/ConduitAdmin.ts
- packages/commons/src/modules/Core/index.ts
- packages/commons/src/modules/Router/interfaces/Router.ts
- packages/commons/src/modules/Security/ConduitSecurity.ts
- packages/commons/src/modules/index.ts
- packages/config/src/admin/routes/GetConfig.route.ts
- packages/config/src/admin/routes/UpdateConfig.route.ts
- packages/config/src/index.ts
- packages/core/src/Core.ts
- packages/router/src/index.ts
- packages/security/src/index.ts
Adds `setConfig()` to configurable core module abstract classes and interfaces in `commons` sdk.
Fixes `set/getConfig()` not working for `admin`, `router`.
Adds `set/getConfig()` for `security`.
> fix(commons,config,core,router,admin,security): config update

- packages/security/src/admin/routes/CreateSecurityClient.route.ts
- packages/security/src/utils/security.ts
Checking if the request.origin ends with the given domain string
> fix(security): regex validation issue

- packages/router/src/admin/routes/GenerateGraphQlClient.route.ts
- packages/router/src/admin/routes/GenerateRestClient.route.ts
- packages/router/src/admin/routes/GetMiddlewares.route.ts
- packages/router/src/index.ts
> fix(router): get middlewares route bug fixed

- libraries/grpc-sdk/src/modules/config/index.ts
- packages/config/src/index.ts
- packages/core/src/core.proto
Modules attempting to `moduleHealthProbe()` after being removed from `Config.registeredModules` due to inactivity are now successfully reregistered.
> fix(config,grpc-sdk): updateModuleHealth() not reregistering removed modules

- libraries/grpc-sdk/package.json
- modules/authentication/build.sh
- modules/authentication/package.json
- modules/chat/build.sh
- modules/chat/package.json
- modules/database/build.sh
- modules/database/package.json
- modules/email/build.sh
- modules/email/package.json
- modules/sms/build.sh
- modules/sms/package.json
- modules/storage/build.sh
- modules/storage/package.json
- packages/commons/build.sh
- packages/commons/package.json
fix(grpc-sdk): duplicate import of proto-loader
chore(commons,sms,email,database,chat,authentication): use grpc-tools instead of protoc
> chore(commons,sms,email,database,chat,authentication,storage): use grpc-tools instead of protoc

- modules/database/src/admin/admin.ts
- modules/database/src/admin/schema.admin.ts
This PR fixes the query params not being parsed from the get pending schemas endpoint and adds support for search param.
> fix(database): get pending query params not parsed, add search param

- modules/database/src/Database.ts
- modules/database/src/adapters/DatabaseAdapter.ts
- modules/database/src/adapters/mongoose-adapter/index.ts
- modules/database/src/adapters/sequelize-adapter/index.ts
This PR addresses the issue where the database module would begin the introspection process even on unpopulated dbs. An additional check has been added to both database adapters where it first checks whether the db contains any user populated collections/tables before proceeding to introspection.
Fixes #167.
> fix(database): database module triggers introspection on unpopulated dbs

- packages/config/src/index.ts
Setting `DEBUG__DISABLE_INACTIVE_MODULE_REMOVAL` to `true` prevents `Config` from kicking out inactive modules.
This was needed as debugging modules proved to be needlessly annoying for most typical debug sessions ever since fixing Config's inactive module kicking.
I opted for a verbose and descriptive env var instead of something like `DEBUG_MODE` as the modified behavior may still be unsuitable for certain debug sessions, plus we may wish to specifically enable/disable certain operations for debugging going forward.
Either way, it's not meant to be used by end users.
> feat(config): DEBUG__DISABLE_INACTIVE_MODULE_REMOVAL env var

- libraries/grpc-sdk/src/classes/Routing/RouteBuilder.ts
- modules/database/src/admin/admin.ts
- modules/database/src/admin/documents.admin.ts
- modules/database/src/admin/schema.admin.ts
- modules/database/src/controllers/cms/utils.ts
- modules/database/src/migrations/crudOperations.migration.ts
- modules/database/src/migrations/index.ts
- modules/database/src/routes/routes.ts
Options for required authentication in differ crud operations provided.
Admin can decide whenever a CRUD operation can be done from an authenticated user.
Also , admin can decide if a CRUD route is disabled or enabled. 
modelOptions migrated to 
```
"modelOptions": {
"conduit": {
"cms": {
"enabled": true,
"crudOperations": {
"create": {
"enabled": true,
"authenticated": false
},
"read": {
"enabled": true,
"authenticated": false
},
"update": {
"enabled": true,
"authenticated": false
},
"delete": {
"enabled": true,
"authenticated": false
}
}
},
"permissions": {
"extendable": true,
"canCreate": true,
"canModify": "Everything",
"canDelete": true
}
}
},
```
**Usage Example**
```
modelOptions.conduit.cms.create.enabled = …
```
> Crud granularity

- libraries/grpc-sdk/src/classes/ConduitSchema.ts
- modules/database/src/Database.ts
- modules/database/src/adapters/DatabaseAdapter.ts
- modules/database/src/adapters/mongoose-adapter/index.ts
- modules/database/src/adapters/sequelize-adapter/index.ts
- modules/database/src/adapters/utils/collectionName.ts
- modules/database/src/admin/admin.ts
- modules/database/src/admin/schema.admin.ts
- modules/database/src/introspection/mongoose/utils.ts
- modules/database/src/introspection/sequelize/utils.ts
- modules/database/src/models/DeclaredSchema.schema.ts
Disables automatic database introspection on `Database` startup.
A simple collection name check is now performed by default, comparing available db schemas with whatever, if anything, is already available in `DeclaredSchemas`, storing foreign schema collection names in the adapter for later use.
`DeclaredSchemas` is now aware of schemas' collection names.
Any Conduit module schemas attempting to be registered using a used collection name now get their actual collection name prefixed by `cnd_`.
Introspection can still be triggered through a `POST` @ `/admin/database/introspection`.
Added a new admin route (`GET` @ `/admin/database/introspection`) for retrieving information on current introspection state:
- foreignSchemas (schemas that have never been imported)
- foreignSchemaCount
- …
> Disable Database Introspection on Startup

- modules/authentication/src/handlers/local.ts
- modules/authentication/src/handlers/oauth2/OAuth2.ts
- modules/authentication/src/handlers/service.ts
- modules/authentication/src/routes/routes.ts
> fix(authentication): wrong errors thrown in validation

- modules/database/src/introspection/mongoose/utils.ts
This PR fixes the casing for ObjectId types in mongo type extraction.
> fix(database): fix casing for mongo ObjectId types in type extraction

- packages/security/src/admin/routes/CreateSecurityClient.route.ts
- packages/security/src/admin/routes/UpdateSecurityClient.route.ts
- packages/security/src/admin/routes/index.ts
- packages/security/src/index.ts
- packages/security/src/models/Client.schema.ts
This PR adds support for adding optional alias and notes fields when creating client ids in security. It addresses the issue when there are multiple client ids and cannot be distinguished one from another solely from the id.
Solves #192.
> feat: added notes and alias options for creating client ids

- modules/authentication/src/handlers/oauth2/OAuth2.ts
> fix(authentication): wrong param types in OAuth2 requests

- libraries/grpc-sdk/src/classes/ConduitParser.ts
- modules/authentication/src/admin/admin.ts
- modules/chat/src/admin/admin.ts
- modules/database/src/admin/admin.ts
- modules/forms/src/admin/admin.ts
- packages/router/src/controllers/Rest/Swagger.ts
- packages/router/src/controllers/Rest/SwaggerParser.ts
This PR fixes Swagger doc generation, removing any existing schema errors and warnings.
Validation tested with [Swagger Editor](https://editor.swagger.io/).
Also fixes:
- `deleteData` param passed as a body parameter in `Database` module`s `deleteSchema` admin route.
- `deleteData` missing entirely from `deleteSchemas` admin route declaration.
Additionally, a few module route return types have been renamed so as to appease Swagger component ref mappings.
This shouldn't be an issue once Swagger generation automatically registers these based on availlable db models.
Limitations: `query` and `url` params are still not advertised as required by Swagger as of right now.
**The PR fulfills these …
> fix(router,grpc-sdk): swagger generation

- .eslintrc.json
This PR introduces an ESlint configuration file to be used by CodeFactor.
I kept all of the [options CodeFactor defaults to](https://github.com/codefactor-io/default-configs/blob/master/.eslintrc.json), except for a `no-unused-vars.ignoreRestSiblings` that would otherwise complain over unused args in ...rest syntax object destructuring that allows getting rid of object fields in a clean and concise way.
I did not include any fancy pre-commit hooks or anything, just a config file to be used by CodeFactor CI tests.
[Tested in a repo fork.](https://github.com/kon14/Conduit/pull/1)
ESlint rule for CodeFactor CI
> ci: ESlint CodeFactor defaults, @typescript-eslint/no-unused-vars ignoreRestSiblings

- packages/security/src/admin/routes/CreateSecurityClient.route.ts
- packages/security/src/admin/routes/GetSecurityClients.route.ts
- packages/security/src/admin/routes/UpdateSecurityClient.route.ts
- packages/security/src/interfaces/ValidationInterface.ts
- packages/security/src/models/Client.schema.ts
- packages/security/src/utils/security.ts
This PR enforces uniqueness across security client aliases.
We already have a notes field for non-unique descriptions anyway.
Security clients now have a db-level uniqueness constraint, and as such, they are also required on a db-level.
Explicitly passing in an alias on security client creation is still optional as it is otherwise implicitly generated based on the platform type, client id and, in case of web clients, the domain used.
~~This is not a breaking change as the feature is not formally released in a tagged non-release-candidate version.~~
This PR **does** introduce a breaking change related to `createClient` and `updateClient` admin route return types.
Basically, we now return `_id` instead of `id` (plus the remaining missing model fields) as we generally do everywhere else.
I …
> fix(security): security client aliases are not unique

- libraries/grpc-sdk/src/classes/ManagedModule.ts
- libraries/grpc-sdk/src/index.ts
- modules/authentication/src/Authentication.ts
- packages/admin/src/index.ts
- packages/commons/src/modules/Admin/ConduitAdmin.ts
- packages/commons/src/modules/Core/index.ts
- packages/core/src/Core.ts
- packages/core/src/config-manager/admin/routes/UpdateConfig.route.ts
- packages/core/src/config-manager/index.ts
- packages/core/src/config/index.ts
- packages/core/src/core.proto
This PR addresses the following issues:
Config's `updateConfig()`, `addFieldsToConfig()` and `configureModule()` no longer accept an explicit gRPC param. The module name is instead received from the gRPC call's metadata. Meaning only the target module itself can update its configuration going forward.
> fix(grpc-sdk,commons,core,admin): config validation

- modules/database/src/Database.ts
- modules/database/src/adapters/DatabaseAdapter.ts
- modules/database/src/adapters/mongoose-adapter/index.ts
- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
- modules/database/src/adapters/sequelize-adapter/index.ts
- modules/database/src/admin/schema.admin.ts
- modules/database/src/controllers/cms/schema.controller.ts
This PR introduces conduit-based naming for system schema collections. It adds a "cnd_" prefix to conduit system schemas (for new deployments only) to properly distinguish them with custom CMS schemas. It also registers imported schemas with an "imp_" prefix in the declared schema name to mark it as imported upon introspection. 
Upgraded DBs will not be impacted and will maintain their current schema naming.
> Schema collection names renaming (on new deployments)

- packages/core/src/config-manager/admin/routes/PatchConfig.route.ts
- packages/core/src/config-manager/admin/routes/index.ts
- packages/core/src/config-manager/index.ts
Config update route request type is now of type PATCH.
This is actually a Breaking Change, but the commit is not marked as such due to a release candidate for v0.14.0 been already out.
PUT @ /config/moduleName -> PATCH @ /config/moduleName
> chore(core): convert update config to a PATCH route

- libraries/grpc-sdk/src/index.ts
> fix(grpc-sdk): monitorModule() not awaiting module before first callback call

- modules/authentication/src/Authentication.ts
- modules/authentication/src/handlers/local.ts
- modules/authentication/src/routes/index.ts
This PR simplifies `Authentication`'s app route registration process.
Any `Email`-dependent routes are now registered once `Email` is online and serving and `Authentication` no longer attempts to handle `Email` module going offline.
Fixes an issue where email serving status would not propagate down to handlers, resulting in incorrect route registration.
I'm using a timeout so as not to register routes twice whenever `Email`-dependent functionality is enabled and the module is already serving at the time `Authentication` is being brought up.
There's a couple of issues currently preventing this from working as expected, but they're both unrelated to `Authentication` and shouldn't require further changes on this side once resolved:
- `Core`'s `watchModules()` gRPC stream is restarted …
> fix(authentication): email dependent app route registration

- libraries/grpc-sdk/src/modules/config/index.ts
- packages/core/src/config-manager/service-discovery/index.ts
- yarn.lock
> fix(grpc-sdk): module inconsistency on momentary core unavailability

- packages/admin/src/middleware/Admin.middleware.ts
This fixes `Admin`'s unset `MASTER_KEY` env var security warning check not working for new env name.
I kept the older form (`masterkey`) around.
We can cleanup older env names in v0.15 with the next compak break.
> fix(admin): outdated master key warning check

- libraries/grpc-sdk/src/modules/config/index.ts
- modules/router/src/Router.ts
- modules/storage/src/Storage.ts
- packages/admin/src/index.ts
- packages/commons/src/modules/Admin/ConduitAdmin.ts
- packages/core/src/config-manager/index.ts
Fixes `Admin` not handling live config updates.
Fixes `Router` and `Storage` using last configuration during `onConfig()` calls.
We could also fix the Convict schema type, but doing so in `Commons` would require importing the config schema from `Admin`.
> fix(admin,commons,core,grpc-sdk,router,storage): config updates

- libraries/hermes/src/Socket/Socket.ts
- modules/router/src/security/handlers/client-validation/index.ts
This PR addresses a couple of crashes related to socket route reregistration and client validation introduced in `bdde3cdf`.
> fix(hermes,router):  socket registration, security client validation

- libraries/hermes/src/Rest/Swagger.ts
Fixes administrative Swagger's `admin` section including admin configuration routes that should otherwise be placed in `config`.
> fix(hermes): Swagger admin section includes admin config routes

- modules/router/src/admin/routes/Ready.ts
- packages/admin/src/routes/Ready.ts
- packages/core/src/config-manager/admin/routes/GetConfigRoute.ts
- packages/core/src/config-manager/admin/routes/SetConfigRoute.ts
- packages/core/src/config-manager/index.ts
For users migrating from `v0.14.4` (specifically: `b22b93`), a Redis flush is required.
> fix(core,admin,router): router types

- libraries/hermes/src/GraphQl/GraphQL.ts
- packages/admin/src/index.ts
- packages/admin/src/middleware/Auth.middleware.ts
- packages/admin/src/routes/ChangePasswordRoute.ts
- packages/admin/src/routes/CreateAdmin.route.ts
- packages/admin/src/routes/Login.route.ts
Fixes publicly accessible GraphQL queries and mutations being blocked by `Admin`'s auth middleware.
Fixes sdk route (package route) object return types getting json parsed.
Leftover cleanup.
> fix(admin,hermes): GraphQL middleware and return type fixes

- modules/database/src/admin/schema.admin.ts
- modules/email/src/admin/index.ts
- modules/forms/src/admin/index.ts
Fixes certain handlers still returning `totalCount` despite their return signature suggesting they return `count`.
All counts are now in truly consistently returned as `count` across all routes.
Branding this as a bugfix instead of a  breaking change as our route doc already specified that return type.
> fix(database,email,forms): handler returned types not matching declared types

- packages/admin/src/middleware/Auth.middleware.ts
Fixes query param check failing for REST requests containing a `query` body param.
> fix(admin): auth middleware body query check

- libraries/grpc-sdk/src/classes/ManagedModule.ts
- modules/authentication/src/Authentication.ts
- modules/authentication/src/config/index.ts
- modules/chat/src/Chat.ts
- modules/chat/src/config/index.ts
- modules/database/src/Database.ts
- modules/email/src/Email.ts
- modules/email/src/config/index.ts
- modules/forms/src/Forms.ts
- modules/forms/src/config/index.ts
- modules/push-notifications/src/PushNotifications.ts
- modules/push-notifications/src/config/index.ts
- modules/router/src/Router.ts
- modules/router/src/config/index.ts
- modules/sms/src/Sms.ts
- modules/sms/src/config/index.ts
- modules/storage/src/Storage.ts
- modules/storage/src/config/index.ts
- packages/admin/src/config/index.ts
- packages/admin/src/index.ts
- packages/core/src/Core.ts
- packages/core/src/GrpcServer.ts
- packages/core/src/config/index.ts
This PR resolves a bug where config update requests containing extra unknown fields would pollute Convict config objects and result in all subsequent update requests failing for that particular module/Core/Admin until restarting it.
To be precise, that was due to Convict's `load()` function merging JSON objects on top of its existing config instead of replacing it with the incoming object.
> fix: invalid config updates polluting Convict config object

- modules/database/src/admin/documents.admin.ts
- modules/database/src/admin/schema.admin.ts
- modules/database/src/permissions/index.ts
Fixes Database's create schema admin route returning incorrect fields.
I'm not marking this as a Breaking Change as it restores the advertised return signature, which is mostly a superset of the regressed one, except for the `schemaOptions` -> `modelOptions` field name.
This also fixes a couple of promises being awaited twice.
> fix(database): admin create schema return type regression

- modules/database/src/adapters/DatabaseAdapter.ts
- modules/database/src/adapters/mongoose-adapter/index.ts
- modules/database/src/adapters/sequelize-adapter/index.ts
- modules/database/src/admin/customEndpoints/customEndpoints.admin.ts
- modules/database/src/admin/customEndpoints/utils.ts
- modules/database/src/interfaces/ConduitDatabaseSchema.ts
- modules/database/src/models/DeclaredSchema.schema.ts
This PR makes it so that Database's CMS custom endpoints functionality may now utilize schema extensions.
It also introduces a `compiledFields` field for `DeclaredSchema` so as to facilitate custom endpoint creation in `Conduit-UI` and complement db type registration of router types (to be addressed in a followup PR).
> fix(database): DeclaredSchema compiledFields extension field and custom endpoint generation

- libraries/grpc-sdk/src/index.ts
- libraries/grpc-sdk/src/metrics/index.ts
This PR adds the 'conduit_' prefix to all metric names for better grouping.
> refactor(grpc-sdk): add prefix to metric names

- modules/database/src/adapters/DatabaseAdapter.ts
This addresses a bug where incoming gRPC schema registrations would remove a schema's extensions from its adapter model, effectively dropping its extensions until the `Database` gets restarted and the adapters repopulated with the contents of `DeclaredSchema`.
To reproduce:
- Start `Core`
- Debug `Database` and set an extension in `createSchemaFromAdapter()` (or similar)
- Notice how any extended schemas coming from `DeclaredSchemas` list their extensions as expected
- Bring up a module owning an extended schema
- Notice how that same schema is reregistered without any extensions
I'm using a hacky type any cast for the schema object as the schema types are already messed up to the point where it wouldn't be worth attempting to retype this on the spot.
We'll have to clean these up …
> fix(database): gRPC schema registration removing schema extensions from adapter models

- libraries/grpc-sdk/src/index.ts
- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
Fixes a crash where Sequelize would unconditionally attempt to make use of metrics while the feature is disabled.
Fixes `grpc-sdk`'s static `metrics` member being required.
> fix(grpc-sdk,database): crash on unconditional Sequelize metrics

- modules/database/src/admin/customEndpoints/customEndpoints.admin.ts
- modules/database/src/utils/utilities.ts
This PR provides the following fixes:
- Unrebased reference to `ConduitSchema.modelSchema` (now `fields`)
- CMS schema creation/modification failing during `modelOptions` input validation
> fix(database): modelOptions cms validation, unrebased modelSchema reference

- libraries/hermes/src/GraphQl/utils/Request.utils.ts
- libraries/hermes/src/Router.ts
- libraries/hermes/src/Socket/Socket.ts
This PR resolves a bug that previously resulted in an unavailable route middlewares not throwing an
error while no other middlewares are currently registered in the API.
Also fixed GraphQL and WebSockets not logging on error catch.
To reproduce, clear your Router's Redis cache and bring up `Core`, `Database`, `Router`, but not `Authentication` or any other
module providing client middlewares.
Register a custom schema through the CMS and enable authentication in any of its auto-generated CRUD endpoints.
Now perform the aforementioned client request without providing an authorization header.
Notice how the missing `userAuth` middleware does not prevent the request from going through.
The scope of this vulnerability is limited.
`Admin` comes with an initial middleware ootb, meaning it's not …
> fix(hermes): not throwing an error on unavaibable route middlewares (v0.14)

- libraries/hermes/src/GraphQl/utils/Request.utils.ts
- libraries/hermes/src/Router.ts
- libraries/hermes/src/Socket/Socket.ts
This PR resolves a bug that previously resulted in an unavailable route middlewares not throwing an
error while no other middlewares are currently registered in the API.
Also fixed GraphQL and WebSockets not logging on error catch.
To reproduce, clear your Router's Redis cache and bring up `Core`, `Database`, `Router`, but not `Authentication` or any other
module providing client middlewares.
Register a custom schema through the CMS and enable authentication in any of its auto-generated CRUD endpoints.
Now perform the aforementioned client request without providing an authorization header.
Notice how the missing `userAuth` middleware does not prevent the request from going through.
The scope of this vulnerability is limited.
`Admin` comes with an initial middleware ootb, meaning it's not …
> fix(hermes): not throwing an error on unavaibable route middlewares

- libraries/hermes/src/Socket/Socket.ts
- modules/authentication/src/routes/index.ts
- modules/router/src/Router.ts
- packages/admin/src/index.ts
- packages/admin/src/middleware/Auth.middleware.ts
- packages/admin/src/utils/config.ts
- packages/commons/src/modules/Config/index.ts
- packages/core/src/config-manager/index.ts
This PR deprecates the following legacy compatibility options in preparation for `v0.15`:
-  Admin / Router http and socket env variables 
- `registerModulesConfig` config gRPC call
-  Admin / Router http and socket env variables 
-  Admin / Authentication (Router) Authorization header JWT-prefixed format (use `Bearer`)
Admin:  `PORT` -> `ADMIN_HTTP_PORT,  SOCKET_PORT` -> `ADMIN_SOCKET_PORT`
Router:  `PORT` -> `CLIENT_HTTP_PORT, SOCKET_PORT` -> `CLIENT_SOCKET_PORT`
> chore(core,admin,router,authentication): deprecate legacy compat options

- libraries/hermes/src/GraphQl/GraphQL.ts
- libraries/hermes/src/Rest/Rest.ts
Fixes a bug where named route response types where handled as string responses.
> fix(hermes): named route response types handled as string responses

- modules/database/src/Database.ts
- modules/database/src/adapters/DatabaseAdapter.ts
- modules/database/src/admin/schema.admin.ts
Fixes the following bugs:
- Admin schema deletion route deleting schemas twice
- Database module recovering `DeclaredSchemas` twice and registering imported schemas with `imported=false`
> fix(database): startup model recovery, deleteSchema admin route

- libraries/hermes/src/GraphQl/GraphQL.ts
- modules/email/src/admin/index.ts
- modules/router/src/admin/router.ts
- packages/admin/src/routes/ChangePassword.route.ts
- packages/admin/src/routes/ChangeUsersPassword.route.ts
- packages/admin/src/routes/CreateAdmin.route.ts
- packages/admin/src/routes/DeleteAdminUser.route.ts
- packages/admin/src/routes/Login.route.ts
- packages/admin/src/routes/ToggleTwoFa.route.ts
- packages/admin/src/routes/VerifyQrCode.route.ts
- packages/admin/src/utils/auth.ts
- packages/core/src/config-manager/admin/routes/GetConfigRoute.ts
- packages/core/src/config-manager/admin/routes/GetModules.route.ts
- packages/core/src/config-manager/admin/routes/SetConfigRoute.ts
This PR fixes GraphQL mutation result nesting (as fix in #331 only addressed queries).
It also removes any verbose route handler result-nesting where redundant.
The latter should not affect the actual response type or doc generation.
> fix(hermes): GraphQL mutation result nesting

- libraries/grpc-sdk/src/helpers/RoutingUtilities.ts
- libraries/grpc-sdk/src/helpers/wrapRouterFunctions.ts
- libraries/grpc-sdk/src/interfaces/Indexable.ts
- libraries/grpc-sdk/src/interfaces/Route.ts
- libraries/grpc-sdk/src/types/index.ts
- libraries/hermes/src/GraphQl/GraphQL.ts
- libraries/hermes/src/Rest/util.ts
- libraries/hermes/src/utils/GrpcConverter.ts
Exposes `cookies` inside route request object for REST and GraphQL API requests.
> feat(grpc-sdk,hermes): rest/graphql cookies support

- modules/authentication/src/handlers/common.ts
- modules/authentication/src/handlers/tokenProvider.ts
- modules/authentication/src/routes/middleware.ts
Provides support for user auth token renewal via a cookie refresh header.
Fixes `Authontication` builds after `cookieOptions` external config field removal.
Depends on #358.
BREAKING CHANGE:
Auth token renewal route now accepts a bearer-formatted refreshToken header or cookie, previously provided as a body param.
> feat(authentication): auth refactor additions

- modules/database/src/admin/schema.admin.ts
- modules/database/src/models/DeclaredSchema.schema.ts
Fixes getSchemas()'s `owner` and `enabled` filters.
Introduces a db level uniqueness constraint on `DeclaredSchema`'s `collectionName` field.
> fix(database): getSchemas filters, declared schema collectionName uniqueness constraint

- libraries/grpc-sdk/src/classes/GrpcServer.ts
- libraries/grpc-sdk/src/helpers/wrapGrpcFunctions.ts
- modules/authentication/src/migrations/configMigration.ts
- packages/admin/src/index.ts
fix(authentication): migration not waiting for Config schema
feat(grpc-sdk): add refresh postpone function to decrease race conditions
> fix(grpc-sdk): server restart race conditions

- libraries/grpc-sdk/package.json
- libraries/grpc-sdk/src/classes/ConduitModule.ts
- libraries/grpc-sdk/src/classes/GrpcServer.ts
- libraries/grpc-sdk/src/helpers/wrapGrpcFunctions.ts
- yarn.lock
This PR introduces gRPC client request retries.
Retries only occur on main service clients (that is to say, not health check clients) for `unavaliable` gRPC error types.
> feat(grpc-sdk): gRPC retries for unavailable services

- modules/authentication/src/Authentication.ts
- modules/authentication/src/handlers/common.ts
- modules/authentication/src/handlers/local.ts
- modules/authentication/src/handlers/magicLink.ts
- modules/authentication/src/handlers/oauth2/OAuth2.ts
- modules/authentication/src/handlers/phone.ts
- modules/authentication/src/handlers/service.ts
- modules/authentication/src/handlers/tokenProvider.ts
- modules/authentication/src/handlers/twoFa.ts
- modules/authentication/src/routes/index.ts
Fixed a bug where attempting to use `TokenProvider` without `Router` (through gRPC) would fail as the singleton was only initialized inside route handlers.
Also improved `TokenProvider.getInstance()` ergonomics.
TokenProvider is now initialized early enough to be used by gRPC requests when there's no Router available.
> fix(authentication): TokenProvider singleton init Router dependency

- modules/storage/src/admin/index.ts
This PR introduces a search query param for `Storage`'s admin API getFolders() route.
Can be combined with existing `parent` query param.
I also introduced default pagination values for the getFiles() admin route (previously required).
Feature was requested by Conduit-UI.
> feat(storage): getFolders() admin search query param

- libraries/grpc-sdk/src/index.ts
- libraries/grpc-sdk/src/utilities/Logger.ts
- libraries/grpc-sdk/src/utilities/index.ts
- libraries/grpc-sdk/src/utilities/linearBackoffTimeout.ts
- modules/database/src/adapters/sequelize-adapter/index.ts
- packages/core/src/config-manager/service-discovery/index.ts
Loki is now only initialized as a logger transport after it becomes available and ready to serve.
Connection is attempted 15 times using linear backooff, with a starting delay of 250ms.
Failing that, no more checks are currently performed until module restart.
> fix(grpc-sdk): loki availability checks

- modules/authentication/src/config/config.ts
- modules/authentication/src/handlers/twoFa.ts
- modules/authentication/src/models/TwoFactorBackUpCodes.schema.ts
- modules/authentication/src/models/index.ts
This PR introduces the generation of back up codes for 2FA.
When authenticated, the user can create 10 one-time-use codes for access recovering, when 2FA isn't possible at that moment.
After being used, each code gets deleted, so the user has to generate more when only a few of them are left. 
> feat(authentication): 2fa backup codes

- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
- modules/database/src/controllers/cms/utils.ts
- modules/database/src/controllers/customEndpoints/customEndpoint.controller.ts
- modules/database/src/handlers/CustomEndpoints/customEndpoint.handler.ts
- modules/database/src/handlers/cms/handler.ts
- modules/database/src/handlers/cms/utils.ts
- modules/database/src/interfaces/Sort.ts
- modules/database/src/interfaces/index.ts
> fix(database): route declare order for crud

- libraries/grpc-sdk/src/routing/wrapRouterFunctions.ts
This allows for router requests to be terminated before the promise resolves. This is useful if a function wants to continue processing some data, AFTER it successfully responded to the user. Previously this was not possible, but now it is.
It's able to use a hybrid of these solutions as well. You may respond using the callback depending on one condition, but if the condition is not satisfied you can respond with the promise resolution.
Also, if a handler does not return data either by callback or by the promise resolve, the wrapper will now throw an error towards the client, informing that no data was received from the handler.
If adding a **new …
> feat(grpc-sdk): support for early request termination in router

- modules/database/src/adapters/mongoose-adapter/index.ts
- modules/database/src/adapters/sequelize-adapter/index.ts
- modules/database/src/admin/documents.admin.ts
> fix(database): schema extensions

- modules/email/src/admin/index.ts
- modules/router/src/admin/index.ts
- modules/router/src/admin/router.ts
- packages/core/src/config-manager/admin/routes/GetModules.route.ts
Routes which support sorting option:
- /config/modules
- /router/routes
- /router/middlewares
- /email/externalTemplates
> Sorting option in core,email and router routes.

- docker/.env
- docker/docker-compose.yml
This PR changes Docker compose's default MongoDB database name to `conduit` (previously `test`).
This is going to break persistent updates (once) across existing demo deployments (once), but seeing as we also have a persistent volume bug in `CLI` (new volume names across versions, [fix here](https://github.com/ConduitPlatform/CLI/pull/34)) and as the existing volumes or`test` dbs are unused, but not technically deleted, I figured it'd be worth doing this now.
We could also have upcoming CLI versions overwrite the previous behavior for older release tags, but it's probably not worth the effort as CLI deployments are demo-oriented.
> build: docker compose rename default mongodb db

- modules/database/src/admin/customEndpoints/customEndpoints.admin.ts
- modules/database/src/admin/customEndpoints/utils.ts
Custom GET endpoints can not have body parameters.
Before this fix , body parameters could be given to a custom GET endpoint.
So, this fix checks if body parameters have been given to a custom GET request.
> fix(database): body params getting in GET requests

- libraries/grpc-sdk/src/interfaces/Model.ts
- libraries/hermes/src/GraphQl/GraphQlParser.ts
- libraries/hermes/src/Rest/Swagger.ts
- libraries/hermes/src/Rest/SwaggerParser.ts
- libraries/hermes/src/classes/ConduitParser.ts
- modules/authentication/src/admin/index.ts
Conduit did not support description in route parameters.
Now , both GraphQL and Swagger parsers in hermes library support it.
Also field descriptions inside route responses supported.
> feat(hermes,grpc-sdk): route field descriptions support

- libraries/grpc-sdk/src/index.ts
- libraries/hermes/src/Socket/Socket.ts
- libraries/hermes/src/index.ts
- modules/router/src/Router.ts
- modules/router/src/security/handlers/rate-limiter/index.ts
- modules/router/src/security/index.ts
- packages/admin/src/index.ts
feat(grpc-sdk): expose redis manager to clients can be created
> fix(router,admin,hermes): new redis options compatibility

- modules/database/src/admin/customEndpoints/utils.ts
- modules/database/src/controllers/customEndpoints/utils.ts
Location Enum to describe custom endpoints parameters was necessary for consistency reasons
> refactor(database): custom endpoints location enum

- libraries/grpc-sdk/src/interfaces/RawQuery.ts
- libraries/grpc-sdk/src/interfaces/index.ts
- libraries/grpc-sdk/src/modules/database/index.ts
- libraries/grpc-sdk/src/types/db.ts
- modules/database/src/Database.ts
- modules/database/src/adapters/DatabaseAdapter.ts
- modules/database/src/adapters/mongoose-adapter/index.ts
- modules/database/src/adapters/sequelize-adapter/index.ts
- modules/database/src/database.proto
This PR adds a new rpc for raw query execution.
A raw query in the rpc can be like this:
```javascript
rawQuery = {
mongoQuery: {
insertOne?: {
_id: 'example',
username: 'example'
},
options?: {
example: true
}
},
sqlQuery: {
query: 'SELECT * FROM "cnd_User"',
options?: {
example: true
}
}
}
```
> feat(database,grpc-sdk): raw query support

- docker/get-conduit.sh
> feat: get-conduit.sh --no-deploy flag

- modules/authentication/src/admin/user.ts
> fix(authentication): admin patch user twoFaMethod

- libraries/grpc-sdk/package.json
- libraries/grpc-sdk/src/classes/ConduitServiceModule.ts
Fixes `grpc-sdk` build missing gRPC health checking proto file, resulting in out-of-tree modules being unable to initialize.
> build(grpc-sdk): fix build missing gRPC health check proto file

- docker/get-conduit.sh
Fixes installation oneliner failing to detect arm64 architecture on Linux.
Fixes Linux arm tarball url.
Adds a $PATH reload hint on new installations so that users are not confused over `conduit` not being available in their parent terminal session (auto-sourcing the rc file is not portable or reliable)
> fix: get-conduit.sh linux arm64 detection

- libraries/grpc-sdk/src/classes/ConduitModule.ts
- libraries/grpc-sdk/src/index.ts
- libraries/grpc-sdk/src/modules/admin/index.ts
- libraries/grpc-sdk/src/modules/authentication/index.ts
- libraries/grpc-sdk/src/modules/authorization/index.ts
- libraries/grpc-sdk/src/modules/chat/index.ts
- libraries/grpc-sdk/src/modules/config/index.ts
- libraries/grpc-sdk/src/modules/core/index.ts
- libraries/grpc-sdk/src/modules/database/index.ts
- libraries/grpc-sdk/src/modules/email/index.ts
- libraries/grpc-sdk/src/modules/forms/index.ts
- libraries/grpc-sdk/src/modules/pushNotifications/index.ts
- libraries/grpc-sdk/src/modules/router/index.ts
- libraries/grpc-sdk/src/modules/sms/index.ts
- libraries/grpc-sdk/src/modules/storage/index.ts
- packages/core/src/config-manager/service-discovery/index.ts
This PR improves `grpc-sdk`'s support for dynamic module clients.
`grpc-sdk` may now automatically initialize `ConduitModule` clients for out-of-tree modules.
This change allows Conduit to handle the configurations for third-party modules.
Custom microservices may explicitly utilize `importDynamicModuleDefinition()` to provide service definition details for initializing a service client.
[Here](https://github.com/kon14/ConduitModuleExample)'s an example module implementation for testing this.
Make sure you update the default `.env` file (defaults to dockerized enviroment support)
> feat(grpc-sdk): dynamic module clients

- libraries/grpc-sdk/src/classes/ConduitModule.ts
- libraries/grpc-sdk/src/index.ts
- libraries/grpc-sdk/src/modules/config/index.ts
- packages/core/src/config-manager/service-discovery/index.ts
This PR cleans up `grpc-sdk` module client initialization and renames certain types and variables so as to improve readability and code clarity (or so I would hope).
It also fixes `serving-modules-update` (broken in `next` due to inconsistent message type publishing) and fixes a 0->false evaluation in `Core` resulting in unknown health states being considered unhealthy (also only affecting `next`).
> fix(grpc-sdk): serving-modules-update

- libraries/grpc-sdk/src/classes/ManagedModule.ts
- libraries/grpc-sdk/src/utilities/index.ts
- libraries/grpc-sdk/src/utilities/merge.ts
- libraries/grpc-sdk/src/utilities/sleep.ts
- packages/admin/src/index.ts
- packages/core/src/config-manager/config-storage/index.ts
This PR fixes config object patches, where array fields would previously get merged.
Previously patching `{ a: true, b: [1, 2, 3] }` with `{ b: [3] }` resulted in `{ a: false, b: [3, 2, 3] }`.
With fix, the above patch results in `{ a: true, b: [3] }`.
> fix(grpc-sdk,admin): config object patch array field merging

- modules/authentication/src/migrations/index.ts
This is a dirty workaround for `Authentication`'s crashing PostgreSQL migrations.
This should be replaced by raw sql migrations in v0.16.
> fix(authentication): crash on PostgreSQL migrations

- modules/database/src/Database.ts
- modules/database/src/adapters/DatabaseAdapter.ts
- modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts
- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
- modules/database/src/interfaces/ConduitDatabaseSchema.ts
- modules/database/src/interfaces/SchemaAdapter.ts
This PR fixes Sequelize populations through.
SequelizeSchema now implicitly handles population relations in `findOne()`, `findMany()` and `findByIdAndUpdate()`.
This bug resulted in populations not working through the client API etc.
> fix(database): sequelize populations

- modules/authentication/src/handlers/oauth2/OAuth2.ts
This PR fixes the following issues in regards to OAuth2 authentication url construction:
- `code_challenge` and `code_challenge_method` passed as `undefined` when not explicitly used by provider
- activation url query params not being prefixed by `?`
> fix(authentication): OAuth2 authentication url construction

- docker/get-conduit.sh
This PR updates `get-conduit.sh` to be POSIX compatible.
It still only adds the CLI to the executable $PATH for bash and zsh, but the script itself is more portable.
> fix: get-conduit.sh not being POSIX compatible

- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
Fixes an adapter bug where SDL findMany() populate caching resulted in all populated fields being assigned the same value.
> fix(database): sql findMany() populates cache identifier uniqueness

- libraries/hermes/src/GraphQl/GraphQL.ts
- libraries/hermes/src/Rest/Rest.ts
- libraries/hermes/src/Rest/util.ts
This PR fixes numeric param parsing in REST and GraphQL so that numeric args are actually passed as true numbers (instead of stringified ones).
This fix currently further **breaks Sequelize** numeric comparisons (eg $gte) as these normally expect a true number, yet somehow only seem to work for stringified numbers despite models representing fields as floats.
Needs further investigation.
> fix(hermes): numeric param parsing, REST middleware running before param validation

- libraries/grpc-sdk/package.json
- libraries/grpc-sdk/src/interfaces/Model.ts
- modules/database/src/adapters/sequelize-adapter/utils.ts
- yarn.lock
This PR includes the following fixes:
- Database's sql parseQuery() failing to parse numeric values
- grpc-sdk depending on sequelize (not @types/sequelize) being available
> fix(database,grpc-sdk): sql parseQuery numeric parsing, grpc-sdk depending on sequelize

- modules/database/src/admin/index.ts
Fixes schema index deletion admin route expecting `indexNames` as body params in a `DELETE` request.
This is technically a breaking change in the admin API, but it reality shouldn't affect end users + UI already expected query params.
> fix(database): schema index deletion admin route invalid param type

- libraries/grpc-sdk/src/types/db.ts
- modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts
- modules/database/src/adapters/mongoose-adapter/parser/index.ts
- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
- modules/database/src/adapters/sequelize-adapter/parser/index.ts
- modules/database/src/admin/customEndpoints/customEndpoints.admin.ts
- modules/database/src/admin/schema.admin.ts
- modules/database/src/handlers/CustomEndpoints/utils.ts
- modules/database/src/interfaces/CustomEndpointsQuery.ts
This PR adds `$like` and `$ilike` operators, introducing support for case-insensitive SQL like comparisons.
Like-strings are now wrapped in `%` instead of `.*`. Eg: `.*abc.*` -> `%abc%`.
~~Custom endpoint queries are to be migrated over to the new format.~~
Custom endpoint syntax has been updated to remain compatible with legacy `{ like: boolean }`.
Specify `{ like: true, caseSensitiveLike: true }` for case-sensitive search.
This change does not affect the underlying `$like` / `$ilike` implementation. 
TODOs:
Not a breaking change as custom endpoints are to be auto-migrated over.
> feat(database): like,ilike operators

- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
Fixes SQL `deleteOne`/`deleteMany` not returning deletion count.
Syntax is somewhat sketchy as Sequelize's `{ returning: true }` wouldn't behave as expected (plus it wouldn't work on all db engines anyway).
> fix(database): sql deleteOne/Many not returning deletion count

- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
- modules/database/src/adapters/sequelize-adapter/utils/schema.ts
There was a bug when creating or updating objects that contained relations. This has been fixed, so I re-enabled foreign keys properly.
> fix(database): relationObjects

- modules/storage/src/handlers/file.ts
- modules/storage/src/providers/azure/index.ts
fix(storage): public url not updated when updating file properties
fix(storage): azure blob Sas not returning proper filenames
> fix(storage): public url not updating & azure Sas urls

- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
- modules/database/src/adapters/sequelize-adapter/parser/index.ts
This PR resolves an issue where SQL like/ilike queries could contain ambiguous field names.
> fix(database): ambiguous SQL like/ilike query fields

- libraries/hermes/src/GraphQl/utils/TypeUtils.ts
Fixes a GrahpQL bug where find by id queries wouldn't get populated.
> fix(hermes): GraphQL population detection

- modules/database/src/adapters/DatabaseAdapter.ts
- modules/database/src/admin/schema.admin.ts
fix(database): getSchemas admin query not working as expected
> fix(database): schemas not being stored

- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
- modules/database/src/adapters/sequelize-adapter/postgres-adapter/SchemaConverter.ts
Fixes PostgreSQL/SQL nested populations not being calculated during queries.
> fix(database): sequelize nested populations

- modules/database/src/adapters/mongoose-adapter/parser/index.ts
- modules/database/src/adapters/sequelize-adapter/parser/index.ts
- modules/database/src/admin/index.ts
**Fixes:** 
- ObjectId cast error when parsing query in mongoose
- The type of [ConduitString.Required] in query params causes a param to be returned as a string and not as an array of strings
> fix(database): fix mongoose & sequelize parseQuery & query param types

- modules/database/package.json
- modules/database/src/Database.ts
- modules/database/src/adapters/sequelize-adapter/index.ts
- modules/database/src/adapters/sequelize-adapter/parser/index.ts
- modules/database/src/adapters/sequelize-adapter/utils/collectionUtils.ts
With this PR, now, querying an embedded json key in sql (besides postgres that didn't have any problem anyway) is possible.
Mssql won't be supported (at least for now), due to lack of proper JSON datatype.  
> refactor(database): removal of mssql & additional parsing for json queries in sql

- modules/authentication/src/config/teams.config.ts
- modules/authentication/src/handlers/team.ts
feat(authentication): add option for teams to add without invite
feat(authentication): add request to fetch invites
fix(authentication): invitation tokens not setting token value
> feat(authentication): expand teams functionality

- modules/storage/src/handlers/file.ts
- modules/storage/src/routes/index.ts
fix(storage): size not being used on upload/update by url
> fix(storage): wrong return signature on upload by url

- libraries/grpc-sdk/src/classes/ModuleManager.ts
- libraries/grpc-sdk/src/index.ts
- libraries/grpc-sdk/src/utilities/env.ts
- libraries/grpc-sdk/src/utilities/index.ts
This PR updates url remapping functionality so as to support explicit domain remap pairs.
The `URL_REMAP` env optionally accepts any of the following:
- a stringified JSON object containing the mappings (format: `{ [url: string]: string }` where url key is the original url and value is the remapped url)
- a path string pointing to a JSON file containing the same configuration as above
- a **single** host address value to remap every client with, keeping the original port (mirroring previous implementation)
Configuration may explicitly contain a wildcard key (`*`) to remap every non-explicitly mapped host address (preserving original ports). This may be used in conjunction with explicit remap pairs.
Url remap functionality no longer affects Redis host configuration (use …
> feat(grpc-sdk): url remap object config

- libraries/grpc-sdk/src/classes/ConduitModule.ts
- modules/authentication/package.json
- modules/authentication/src/config/config.ts
- modules/authentication/src/routes/middleware.ts
- modules/authentication/src/utils/index.ts
- modules/forms/src/config/config.ts
- modules/forms/src/controllers/forms.controller.ts
- modules/forms/src/routes/index.ts
- modules/router/package.json
- modules/router/src/config/config.ts
- modules/router/src/security/handlers/captcha-validation/index.ts
- modules/router/src/security/index.ts
- packages/admin/src/config/config.ts
> feat(authentication, router,forms): global captcha support from router

- libraries/grpc-sdk/src/modules/storage/index.ts
- modules/storage/src/Storage.ts
- modules/storage/src/adapter/StorageParamAdapter.ts
- modules/storage/src/admin/index.ts
- modules/storage/src/handlers/file.ts
- modules/storage/src/routes/index.ts
- modules/storage/src/storage.proto
**Fixes:**
- Storage rpc function params 
- Container param missing in createFileRequest & updateFileRequest in protofile
- Add missing updated file to response of admin route createFileByUrl & both UpdateFileByUrl endpoints
> fix(storage,grpc-sdk): fix storage rpc functions

- modules/database/src/adapters/mongoose-adapter/parser/index.ts
- modules/database/src/handlers/CustomEndpoints/utils.ts
This PR resolves PostgreSQL/SQL like/ilike customEndpoint queries escaping regexp characters.
> fix(database): sql like/ilike customEndpoint queries regexp escaping

- modules/database/src/adapters/sequelize-adapter/utils/schema.ts
Fix: foreign keys referencing to wrong table in M:N associations
**Important: This fix requires a database wipe on SQL databases**
> fix(database)!: wrong foreign key names

- modules/database/src/adapters/utils/validateFieldChanges.ts
> fix(database): adding/removing object(group) fields not working

- modules/storage/src/storage.proto
This is a workaround until we introduce proper int64 support.
> fix(storage): createFileByUrl/updateFileByUrl gRPC size field types

- modules/functions/src/Functions.ts
- modules/sms/src/Sms.ts
This PR resolves a startup error where admin route registrations would be attempted before module service registration, resulting in `getModuleUrlByName()` failing to retrieve the service url.
> fix(functions,sms): admin route registration before module registration errors

- libraries/grpc-sdk/src/interfaces/Route.ts
There's currently 2 ways to define a route param field representing an array of types (assuming str):
- a) `[{ type: [TYPE.String], required: true }]` (shorthand: `[ConduitString.Required]`)
- b) `{ type: [TYPE.String], required: true }`
We generally use both of these interchangeably, with Swagger and GraphQL both currently interpreting them in their own fashion. Namely:
- Swagger handles `(a)` as `string` and `(b)` as `required string[]`
- GraphQL handles both as `[String]!`
We should eventually fix the parsers and consistently infer `(a)` as a nullable array of required strings (aka as in GQL: `[String!]`) and `(b)` as a non-null array of strings (aka `[String]!`) across transports and query/body params.
This PR resolves `ConduitQueryParams` not accepting `(a)` on a type-level.
**What …
> fix(grpc-sdk): ConduitQueryParams type disallowing required object-formatted array param definition

- modules/database/src/adapters/SchemaAdapter.ts
- modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts
- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
This PR resolves an SQL adapter issue where authorized `findMany()` calls would parse native Sequelize queries (containing operator symbols as opposed to object keys), resulting in the final queries getting stripped off of any such conditions (eg `$and`, `$or` etc).
> fix(database): authorized SQL findMany() queries

- modules/database/src/Database.ts
- modules/database/src/permissions/index.ts
fix(database): canCreate permission check using wrong field
fix(database): canModify not checking for extension permissions
refactor(database): rpc queries use new canModify arg when modify but not when replace
> fix(database): permission checks for extensions

- modules/database/src/adapters/sequelize-adapter/parser/index.ts
Eg: `{ foo: { $eq: null }}` -> `{}`
> fix(database): _parseQuery() dropping query fields

- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
- modules/database/src/adapters/sequelize-adapter/parser/index.ts
- modules/database/src/adapters/sequelize-adapter/utils/pathUtils.ts
This PR resolves the following issues in SQL:
- `createMany()` not parsing relation field inputs (eg `user -> `userId`)
- `create()`/`createMany()` not reverse parsing relation field responses
- `create()`/`createMany()` not reverse parsing group field responses (eg `group_field` -> `{ group: { field: ... } }`)
> fix(database): SQL create/createMany relation parsing, group unwrapping

- modules/database/src/adapters/DatabaseAdapter.ts
- modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts
- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
This PR resolves the following `Database` timestamps (`createdAt`, `updatedAt`) issues:
1) SQL schema doc creation timestamp mismatch (`create()`, `createMany()`)
2) SQL/Mongo adapter operations explicitly setting timestamp field values regardless of `modelOptions.timestamp`
3) Schema extension creation timestamps mismatch
In regards to [2]:
`Sequelize` completely ignored explicit query timestamp values.
`Mongoose` would use provided values, but doesn't really require setting them anyway.
> fix(database): schema/extension creation timestamp field values mismatch

- libraries/hermes/src/GraphQl/GraphQlParser.ts
- libraries/hermes/src/Rest/SwaggerParser.ts
This PR resolves a Hermes bug where Swagger and GraphQL parsers wouldn't flag related schema types as requested, resulting in said types never getting fetched from the db schema type registry.
Example:
Create schemas A (no CRUD or custom endpoints), B (contains a relation to A and a CRUD endpoint).
Parsers will generate schemas for B, mentioning the relation to A, but A wouldn't get it's own type declared in the schema.
> fix(hermes): Swagger/GraphQL parsers not pulling related db schema types

- libraries/grpc-sdk/tsconfig.json
- libraries/hermes/tsconfig.json
- libraries/module-tools/tsconfig.json
- libraries/node-2fa/tsconfig.json
- libraries/testing-tools/tsconfig.json
- modules/authentication/tsconfig.json
- modules/authorization/tsconfig.json
- modules/chat/tsconfig.json
- modules/database/tsconfig.json
- modules/email/tsconfig.json
- modules/forms/tsconfig.json
- modules/functions/tsconfig.json
- modules/push-notifications/tsconfig.json
- modules/router/tsconfig.json
- modules/sms/tsconfig.json
- modules/storage/tsconfig.json
- packages/admin/tsconfig.json
- packages/commons/tsconfig.json
- packages/core/tsconfig.json
This PR resolves a huge bug around `await` usage in gRPC handlers being incorrectly transpiled into `yield` outside generators.
Example (a section of `Database` module's `createView()` gRPC handler):
```typescript
try {
await this._activeAdapter.createView(
call.request.schemaName,
call.request.viewName,
call.request.joinedSchemas,
call.request.query,
);
callback(null);
} 
```
This should in theory transpile into code that only executes the callback after the promise has returned.
Alas we got this:
``` javascript
try {
yield this._activeAdapter.createView(call.request.schemaName, call.request.viewName, call.request.joinedSchemas, call.request.query);
callback(null); // @dirty-type-cast
}
```
Modifying the original TypeScript code so that the callback would execute inside a `.then()` …
> fix: gRPC await promise transpilation, bump ECMAScript target to ES2018

- libraries/grpc-sdk/tsconfig.json
- libraries/hermes/tsconfig.json
- libraries/node-2fa/tsconfig.json
- libraries/testing-tools/tsconfig.json
- modules/authentication/tsconfig.json
- modules/authorization/tsconfig.json
- modules/chat/tsconfig.json
- modules/database/tsconfig.json
- modules/email/tsconfig.json
- modules/forms/tsconfig.json
- modules/functions/tsconfig.json
- modules/push-notifications/tsconfig.json
- modules/router/tsconfig.json
- modules/sms/tsconfig.json
- modules/storage/tsconfig.json
- packages/admin/tsconfig.json
- packages/commons/tsconfig.json
- packages/core/tsconfig.json
This is a backport of #689 for `v0.15`
> fix: gRPC await promise transpilation, bump ECMAScript target to ES2018 (v0.15 #689 backport)

- packages/core/src/utils/index.ts
This PR resolves an issue around config schema array field parsing.
Bug can be reproduced via [kon14/ConduitModuleExample](https://github.com/kon14/ConduitModuleExample/).
Config schema includes an array field (`illegalNames`) that results in the issue manifesting during route schema generation (GraphQL explicitly throws as the schema is atomically treated as invalid).
> fix(core): config schema array field parsing

- modules/authorization/src/controllers/index.controller.ts
- modules/authorization/src/controllers/relations.controller.ts
This PR introduces a bulk variant for relation index construction.
`ActorIndex.findMany()` calls should probably be squashed into a single `findMany()` query with multiple `AND` cases instead, but I'm opening this one for _constructive criticism_ before handling that.
Co-authored by @Renc17.
> feat(authorization): constructRelationIndexes() bulk variant

- libraries/grpc-sdk/src/index.ts
- libraries/grpc-sdk/src/modules/config/index.ts
- packages/core/README.mdx
- packages/core/src/config-manager/index.ts
- packages/core/src/core.proto
This PR improves Redis configuration in the following ways:
- Modules no longer need to explicitly provide Redis cluster configuration details as that's now directly retrievable through `Core`.
- `grpc-sdk` / `Core` code cleanup around `getRedisDetails()`
It also introduces a `REDIS_DB` env in `grpc-sdk`.
Providing an explicit database option was previously only doable via the `REDIS_CONFIG` stringified config object env.
Backwards compatibility is currently maintained for users of `<=grpc-sdk-v0.16.0-alpha.20`.
> refactor(grpc-sdk,core): getRedisDetails()

- modules/database/src/adapters/SchemaAdapter.ts
- modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts
- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
This PR fixes quite a lot of issues mostly around, but not limited to, authz functionality:
- invalid nullity checks (eg: `isNil([])` isn't really falsy)
- update / delete operations entirely missing Authz parsed query nullity checks
- invalid SQL.deleteMany(), Mongo.deleteOne(), Mongo.deleteMany() response formatting
These effectively end up resolving:
- SQL `findByIdAndUpdate()` missing explicit throw on no doc (db query threw down the line)
- Mongo `updateOne()`/`replaceOne()` operations updating random schema docs
- SQL / Mongo `deleteOne()`/`deleteMany()` operations deleting random schema docs
> fix(database): update/delete operations authz checks, sql authz/dialect parsing order

- modules/authentication/src/handlers/magicLink.ts
This PR fixes the following issues:
- Magic link creation endpoint missing custom `redirectUri` functionality
- Magic link hook endpoint declaration invalid `redirectUri` type
> fix(authentication): sendMagicLink missing redirectUri, magic link hook invalid redirectUri param type

- modules/authentication/src/config/magicLink.config.ts
- modules/authentication/src/handlers/magicLink.ts
- modules/authentication/src/models/Client.model.ts
This PR introduces a configurable magic link dispatch URI config option for customizing magic token consumption.
When provided, magic token emails will link to the specified address, instead of the default magic token hook endpoint.
I've also introduced some str nullity check fixes as well as workarounds for trailing slashes.
This PR also modifies internal `redirectUri` behavior.
These are no longer appended to the magic link as query params and are retrieved from the token doc instead.
Non-overriden `redirectUri` values are intentionally not stored in `token.data` and coalesced back into latest config values during token retrieval (in hook endpoint).
If …
> feat(authentication): configurable magicLink dispatch URI, magic token consumption endpoint

- libraries/hermes/src/Rest/Rest.ts
- libraries/hermes/src/Rest/Swagger.ts
- libraries/hermes/src/index.ts
- modules/router/src/Router.ts
- modules/router/src/hermes/swaggerMetadata.ts
- packages/admin/src/hermes/swaggerMetadata.ts
- packages/admin/src/index.ts
This PR resolves the following Swagger issues:
- Endpoints using optional `authMiddleware?` not listing auth header.
- Security client headers always showing up
I've cleaned up the Swagger refresh logic a bit, while also enabling support for security schemes to be re-evaluated on router refresh (allowing for config updates to effectively affect these).
"Duplicated" security scheme arrays around optional `authMiddleware` are due to [OpenAPI's multi-auth](https://swagger.io/docs/specification/authentication/#multiple).
Essentially an optional header may (array including it) or may not (array omitting it) be required by target scheme.
> fix(hermes,router,admin): Swagger missing optional authMiddleware headers, conditional security client headers

- libraries/grpc-sdk/src/modules/authentication/index.ts
- modules/authentication/src/Authentication.ts
- modules/authentication/src/authentication.proto
- modules/authentication/src/routes/middleware.ts
> feat(authentication,grpc-sdk): ValidateAccessToken gRPC method

- modules/router/src/config/config.ts
- modules/router/src/security/handlers/rate-limiter/index.ts
This PR introduces (limited) configuration options for client API request rate limiting.
Namely, it allows for configuring the maximum amount of requests per interval and interval duration.
-`maxRequests`: Maximum number of allowed user requests per reset interval.
-`resetInterval`: Request count reset timeframe. Expressed in seconds.
-~`exceedQuotaPenaltyDuration`: Penalty duration for which to automatically block any subsequent requests once rate limit is exceeded. Expressed in seconds.~
I was originally going to also expose an option for configuring the timeout period in `exceedQuotaPenaltyDuration`, but given how that could allow admins that are unfamiliar with said mechanic's internals to effectively perma-ban their own, as well as others', IPs by accident, I settled on a hardcoded …
> feat(router): request rate limit configuration

- modules/chat/src/config/config.ts
- modules/chat/src/routes/index.ts
One extra idea, that we should probably think about implementing, is the "auditing" of the chats. This could be enabled optionally, so when a chat is deleted, then it would only be flagged as deleted and not removed from the database. It should also keep track of who and when, entered or left the chat, along with their messages, so that an admin can audit the messages for abuse.
Thinking even more long-term, even if end-to-end encryption was introduced in an app, the user could be able to share encryption keys in order read the actual messages for such cases.
> feat(chat): add config to delete rooms when participants have left

- libraries/grpc-sdk/build.sh
- libraries/grpc-sdk/src/modules/chat/index.ts
- libraries/testing-tools/build.sh
- modules/authentication/build.sh
- modules/authorization/build.sh
- modules/authorization/src/authorization.proto
- modules/chat/build.sh
- modules/chat/src/Chat.ts
- modules/chat/src/chat.proto
- modules/database/build.sh
- modules/email/build.sh
- modules/functions/build.sh
- modules/push-notifications/build.sh
- modules/router/build.sh
- modules/sms/build.sh
- modules/storage/build.sh
- packages/commons/build.sh
This PR disables `ts-proto`'s snake_case to camelCase conversions.
For whatever reason, `ts-proto` seems to match leading underscores as snake_case, even though they're technically not.
Example: message field `_id` would become `Id`
Besides being a nuisance, this resulted in generated types not really working as expected across server/client.
Eg: `Chat` module's `createRoom` was expected to return `Id` server-side and receive the same field client-side, but we actually received an empty string (default gRPC value) instead.
While at it, I also modified `DeleteRoomRequest`s signature to also return `_id` (previously `id` as a workaround).
This should make the API consistent, while also matching the underlying db doc field naming.
The modifications in `Chat`'s proto file are technically a …
> fix: ts-proto snake_case to camelCase, Chat.gRPC.createRoom() empty id res field

- libraries/hermes/src/Rest/Rest.ts
- libraries/hermes/src/Router.ts
This PR resolves a `Hermes` issue around route middleware not updating context values until after the complete middleware chain has finished executing.
In layman's terms, stacked middleware handlers would all access the original context values instead of the the cumulative assignments taking place during middleware chain execution.
> fix(hermes): cumulative middleware context

- modules/authentication/src/config/microsoft.config.ts
- modules/authentication/src/handlers/oauth2/microsoft/microsoft.ts
Currently, AD authentication only supports multi-tenant applications. With this change you can specify the Tenant ID of the application so that single-tenant apps can work.
> refactor(authentication): support tenant-only AD login

- modules/authentication/src/models/BiometricToken.schema.ts
- modules/authentication/src/models/Team.schema.ts
- modules/authentication/src/models/Token.schema.ts
- modules/authentication/src/models/TwoFactorBackUpCodes.schema.ts
- modules/authentication/src/models/TwoFactorSecret.schema.ts
- modules/authentication/src/models/User.schema.ts
- modules/authorization/src/models/ActorIndex.schema.ts
- modules/authorization/src/models/ObjectIndex.schema.ts
- modules/authorization/src/models/Permission.schema.ts
- modules/authorization/src/models/Relationship.schema.ts
- modules/authorization/src/models/ResourceDefinition.schema.ts
- modules/chat/src/models/InvitationToken.schema.ts
> fix: model controller class constructor visibility

- modules/authentication/src/admin/team.ts
- modules/authentication/src/handlers/team.ts
fix(authentication): admin team name change not checking name availability
> feat(authentication): team names no longer have to be unique in general but on parent level

- modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts
This PR fixes a bug in authorized findOne mongoose queries. By giving null query value to mongoose findOne() the first found doc of the model was returned instead of a null value.
> fix(database): missed null parsedQuery case in mongoose findOne()

- modules/database/src/Database.ts
- modules/database/src/adapters/mongoose-adapter/MongooseSchema.ts
- modules/database/src/adapters/sequelize-adapter/SequelizeSchema.ts
This issue was caused by gRPC server implementations not allowing for undefined object values.
According to the gRPC spec, any optional fields that are omitted from the request are to be coalesced with their respective type's default value.
For objects, that would be an empty object.
> fix(database): gRPC findMany() empty sort handling

- modules/router/src/hermes/swaggerMetadata.ts
This PR fixes a Swagger issue were route docs wouldn't list non-global security schemes.
This issue would show up while no other headers were globally requested (eg Security Clients) due to OpenAPI security scheme array entries being mutually exclusive, meaning that either one of the entries could be used to authorize the request, as such any headers that are always requested should be added to each security scheme entry in the array.
Given no other entries to be updated, the previous implementation would fail to append the changes.
Admin is unaffected, as `MasterKey` is always required.
> fix(router): route Swagger doc missing non-global security headers

- modules/database/src/adapters/sequelize-adapter/index.ts
This PR resolves a Postgres/SQL adapter issue where `createSchemaFromAdapter()` would fail due to an underlying engine constraint whenever schema views already exist for the model.
This looks up and **deletes any views for target schema**.
I'm making the following assumptions:
1) Views are a `Database` mechanism that's (currently) **exclusively used by `Authorization`**
2) Views are automatically recreated by `Authorization` on followup queries
We would ideally automatically recreate the views upon recreating the schemas, but it's somewhat complicated.
We can safely recreate any views for schema creations with unchanged fields (or even schema updates that don't affect any relevant fields), but we can't really reuse the stored query string to recreate views with modified fields. …
> fix(database): SQL createSchemaFromAdapter() drop views on schema view exists constraint

- packages/core/src/config-manager/service-discovery/ServiceMonitor.ts
- packages/core/src/config-manager/service-discovery/index.ts
refactor(core): add sanity check for module existence in monitor loop
> fix(core): missing check for double removal of unresponsive module

- modules/authentication/src/handlers/oauth2/OAuth2.ts
- modules/authentication/src/handlers/oauth2/apple/apple.json
- modules/authentication/src/handlers/oauth2/bitbucket/bitbucket.json
- modules/authentication/src/handlers/oauth2/facebook/facebook.json
- modules/authentication/src/handlers/oauth2/figma/figma.json
- modules/authentication/src/handlers/oauth2/github/github.json
- modules/authentication/src/handlers/oauth2/gitlab/gitlab.json
- modules/authentication/src/handlers/oauth2/google/google.json
- modules/authentication/src/handlers/oauth2/linkedIn/linkedin.json
- modules/authentication/src/handlers/oauth2/microsoft/microsoft.json
- modules/authentication/src/handlers/oauth2/reddit/reddit.json
- modules/authentication/src/handlers/oauth2/slack/slack.json
- modules/authentication/src/handlers/oauth2/twitch/twitch.json
- modules/authentication/src/handlers/oauth2/twitter/twitter.json
This PR resolves #854 by omitting the original `?` mark in the provider param objects.
I'm also trimming these off on usage just in case anybody's implementing out-of-tree custom providers.
> fix(authentication): OAuth provider redirect URIs containing double query question marks

- libraries/grpc-sdk/src/classes/ConduitModule.ts
- libraries/grpc-sdk/src/index.ts
- libraries/grpc-sdk/src/modules/config/index.ts
With the current implementation, should the core module shutdown, the modules do not attempt to reconnect to it.  If they try to set config etc, they should re-establish connection but without properly updating their state. At the same time, the module change watcher won't be restarted and the module won't be made aware of any changes.
This PR fixes this issue, by making sure that once the core connection drops, the modules begin trying to reconnect, and restart the watchers upon successful connection.
> fix(grpc-sdk): module connection not re-established after core shutdown

- modules/authentication/src/handlers/local.ts
- modules/authentication/src/utils/index.ts
This PR removes the need for providing the old `User` password during pass change via the `Local` auth strategy.
The route already required `sudo` access (aka a fresh, un-rotated, `accessToken`) so this shouldn't be an issue.
This isn't really breaking any APIs either as `Router` doesn't currently throw on additional body params.
Therefore any outdated applications should still remain functional as-is.
> feat(authentication): rm oldPassword body param from /local/change-password

- packages/admin/src/index.ts
- packages/core/src/GrpcServer.ts
this is done so that initialization errors properly crash the core module, since recovery is not possible at that stage.
This fixes issues that occur if the core module fails to communicate with the database, following a temporary network disruption, resulting in core being partially functional, with no recovery paths.
> refactor(core,admin): remove catch clauses in initialization steps

- modules/authorization/src/Authorization.ts
- modules/authorization/src/admin/relations.ts
- modules/authorization/src/admin/resources.ts
- modules/authorization/src/authorization.proto
- modules/authorization/src/controllers/relations.controller.ts
- modules/authorization/src/controllers/resource.controller.ts
- modules/authorization/src/models/ResourceDefinition.schema.ts
This PR introduces support for `ResourceDefinition` versioning.
Database defaults no longer override explicit definitions.
I've also fixed the following issues:
-ResourceController.updateResourceDefinition() duplicated by-id/by-name methods
-ResourceDefinition/Relationship events using invalid module name prefix
-ResourceDefinition/Relationship events only published via admin API
-Relationship createMany() publishing invalid event data
-'Authorization`'s Admin API endpoint response signatures mismatch *
In regards to the latter:
`getRelations`/`getResources` would previously provide a response signature of `{ relations, count }` and `{ resources, count }` respectively, whilst actually returning `{ found, count }`.
The returned object signature now adheres to the documented endpoint …
> feat(authorization): ResourceDefinition versioning, bus event pub fixes, admin API res signature fixes

- modules/authentication/src/Authentication.ts
- modules/authentication/src/config/config.ts
- modules/authentication/src/handlers/local.ts
- modules/authentication/src/handlers/magicLink.ts
- modules/authentication/src/handlers/oauth2/OAuth2.ts
- modules/authentication/src/handlers/oauth2/apple/apple.ts
- modules/authentication/src/utils/index.ts
This PR extends the usability of `Authentication`'s `redirectUri` req params.
As far as the API is concerned, redirect URIs are now always overridable, in supported endpoints.
Provided URIs however, must be explicitly whitelisted.
Alternatively, custom redirect URIs may be enabled unconditionally.
This option is meant to be used for dev purposes. A warning will be logged while in `production` mode.
The `customRedirectUris` config option has been succeeded by:
`redirectUris: { allowAny: boolean; whitelistedUris: string[] }`
This is technically a minor **Breaking Change**, config-wise as `allowAny` defaults to false and the previous config toggle no longer applies.
**The PR fulfills these …
> feat(authentication): redirectUri overrides expansion

- modules/authorization/src/controllers/index.controller.ts
- modules/authorization/src/controllers/relations.controller.ts
- modules/authorization/src/models/ResourceDefinition.schema.ts
This PR resolves an `Authorization` bug around `MongoDB` deployments.
`ResourceDefinition`'s model controller would previously brand `relations` and `permissions` fields as non-nullable (code-wise), alas `MongoDB` would minimize empty object fields by default.
As a result, doc queries would often come up with `undefined` field values where TypeScript would expect to be working with a non-nullable type field.
Example:  the `User` resource defines no relations by default.
This PR introduces updates the model controller and schema definition to reflect that these fields may actually be missing and introduces relevant checks to accommodate this behavior.
**Possible Alternative:**
Setting MongoDB's `minimize` model option to `false` for any affected schemas.
**Considerations:**
The gRPC spec …
> fix(authorization): ResourceDefinition relations/permissions nullable MongoDB fields handling

- libraries/grpc-sdk/src/index.ts
- libraries/grpc-sdk/src/modules/email/index.ts
- modules/authentication/src/Authentication.ts
- modules/authentication/src/handlers/local.ts
- modules/authentication/src/handlers/magicLink.ts
- modules/authentication/src/handlers/team.ts
- modules/chat/src/utils/index.ts
- modules/email/src/Email.ts
- modules/email/src/admin/index.ts
- modules/email/src/email.proto
- modules/email/src/interfaces/RegisterTemplateParams.ts
- modules/email/src/interfaces/SendEmailParams.ts
- modules/email/src/services/email.service.ts
- modules/forms/src/routes/index.ts
This PR contains the following changes:
The email sender is filled from the template if defined, which is overriden by the send email request if a sender is provided. If neither the request nor the template contain a sender, then a default "no-reply" is added.
Furthermore, the full sender address is checked for compatibility with the registered sending domain in the configuration, and if there is a mismatch a warning is logged in the console. It also fixes an issue where template patches did not update the sender field of the template.
> refactor(email): sender definitions in templates & requests

- packages/core/src/config-manager/service-discovery/index.ts
- packages/core/src/interfaces/IModuleConfig.ts
This solves an issue, where on starting up multiple modules at the same time, resource contention on redis locks would occur, impacting configuration recovery.
> refactor(core): modify HA startup function to reduce redis lock times

- libraries/grpc-sdk/src/modules/authorization/index.ts
- modules/authorization/src/Authorization.ts
- modules/authorization/src/authorization.proto
- modules/authorization/src/controllers/permissions.controller.ts
This PR updates `Authorization`'s `CreateResourceAccessList` RPC so that it:
-returns the newly created view's name in its response (`viewName`)
-optionally accepts an explicit view name via its request (`viewName`)
> feat(authorization,grpc-sdk): CreateResourceAccessList viewName

- libraries/grpc-sdk/src/modules/storage/index.ts
- modules/storage/src/admin/adminFile.ts
- modules/storage/src/admin/index.ts
- modules/storage/src/config/config.ts
- modules/storage/src/handlers/file.ts
- modules/storage/src/interfaces/IFileParams.ts
- modules/storage/src/interfaces/index.ts
- modules/storage/src/models/File.schema.ts
- modules/storage/src/routes/index.ts
- modules/storage/src/storage.proto
- modules/storage/src/utils/index.ts
This PR implements some storage module features mentioned in #1076 
The ``name`` field in storage file requests in now optional & another optional field ``alias`` is introduced. 
This enables creating files with a same alias while storing them with a UUID name
Additionally, a configurable storage feature is introduced - appending a suffix at the end of a name in case of conflict.
This feature is mimicking the way files are traditionally stored in file systems
Finally, while adding the features I did some refactoring to minimize found duplicate code
> feat(storage): file aliases

- libraries/grpc-sdk/src/classes/ConduitAuthorizedResource.ts
- modules/authentication/src/authz/index.ts
- modules/authentication/src/handlers/team.ts
This PR fixes a bug mentioned in issue #1095 that allowed 'editAll' members of a team to delete team's owners
A new permission in Team resource ``deleteOwners`` now gives only the team owner (or however user is granted this permission) the right to remove the owners of the team
``Warning !``
``The addition of the new permission triggers reindexing jobs, as a new version of Team resource is applied !``
> fix(authentication, grpc-sdk): team owner deletion bug

- modules/push-notifications/src/admin/index.ts
- modules/push-notifications/src/config/config.ts
feat(push-notifications): set default state to enabled
In truth the endpoint changes are breaking, but they are not in use really, so I'm kinda cheating here.
> refactor(push-notifications): rework some admin endpoints for the new UI and correctness

- modules/authentication/src/Authentication.ts
- modules/authentication/src/handlers/tokenProvider.ts
This PR includes the following fixes:
1) `TokenProvider.createUserTokens` not throwing for inactive (blocked) users.
2) `UserLogin` RPC not throwing for inactive (blocked) users
3) `GetTeam` RPC not throwing for not-found
I'd much rather return a specific exception type in (1), but it's not technically in a `GrpcError` layer.
Failing early in `UserLogin` both to avoid unnecessary operations and to enforce proper error type (regardless of whatever else `TokenProvider.createUserTokens()` ends up throwing for in the future.
I'd also much rather have `GetTeam` return an optional Team field instead of throwing, but that would constitute a breaking change in the gRPC API contract.
These RPC changes …
> fix(authentication): UserLogin, GetTeam RPCs

- modules/authentication/src/handlers/oauth2/OAuth2.ts
- modules/authentication/src/handlers/oauth2/apple/apple.json
- modules/authentication/src/handlers/oauth2/apple/apple.ts
- modules/authentication/src/handlers/oauth2/bitbucket/bitbucket.json
- modules/authentication/src/handlers/oauth2/facebook/facebook.json
- modules/authentication/src/handlers/oauth2/facebook/facebook.ts
- modules/authentication/src/handlers/oauth2/figma/figma.json
- modules/authentication/src/handlers/oauth2/github/github.json
- modules/authentication/src/handlers/oauth2/gitlab/gitlab.json
- modules/authentication/src/handlers/oauth2/google/google.json
- modules/authentication/src/handlers/oauth2/google/google.ts
- modules/authentication/src/handlers/oauth2/interfaces/OAuth2Settings.ts
- modules/authentication/src/handlers/oauth2/linkedIn/linkedin.json
- modules/authentication/src/handlers/oauth2/microsoft/microsoft.json
- modules/authentication/src/handlers/oauth2/reddit/reddit.json
- modules/authentication/src/handlers/oauth2/slack/slack.json
- modules/authentication/src/handlers/oauth2/twitch/twitch.json
- modules/authentication/src/handlers/oauth2/twitter/twitter.json
This PR introduces a new setting in oAuth handlers for native options. This begun mainly for apple login, but should be implemented in other providers, mainly Facebook and Google. For now both of these providers are left in their current state.
> feat(authentication): supportNative setting in providers

- modules/storage/src/Storage.ts
- modules/storage/src/config/config.ts
- modules/storage/src/interfaces/StorageConfig.ts
- modules/storage/src/providers/aws/index.ts
- modules/storage/src/utils/index.ts
This PR fixes some issues when integrating with non-AWS S3 providers.
- The Storage provider assumed that domain-based routing would always be used for file access since AWS deprecated the functionality. A new config parameter usePathStyle has been added to accommodate path-based routing.
- Public URL construction assumed an AWS deployment, this has been modified to construct the URL based on the provided endpoint if not on AWS
- Public URL construction did not apply region on AWS URLs, which typically won't create an issue, but has been added for clarity
> fix(storage): integration with non-aws providers issues

- modules/authentication/src/Authentication.ts
- modules/authentication/src/handlers/local.ts
- modules/authentication/src/handlers/team.ts
- modules/chat/src/utils/index.ts
Task id: 86c30zbjv
Feat: Set custom variable values in emails sent by conduit
In some cases we want to set additional variables to templates that are used in emails sent by conduit. While it is possible to update the variables array, there is no way to set the variable values when conduit is sending the email.
For example, when a user registers, they have to get a verification email. For this case the EmailVerification template is used and the only variable value set by conduit when sending the email is link
Even if you update the template's variables array, you have to …
> feat(authentication, chat) set custom variable values email

- libraries/grpc-sdk/src/modules/authentication/index.ts
- modules/authentication/src/Authentication.ts
- modules/authentication/src/authentication.proto
Adding userData in userCreate grpc will allow us to set values to User extended fields (like we do in /local/new) & use them in EmailVerification template 
> feat(authentication): add userData in userCreate grpc

- libraries/grpc-sdk/src/interfaces/RawQuery.ts
- modules/database/src/adapters/mongoose-adapter/index.ts
This PR fixes a bug found when I wanted to use updateOne or updateMany through rawQuery(). 
The only way to set both the ``filter`` and the ``update`` query objects, was to put them together as an array (probably that's why we had defined the type as object[]) and the mongoose updateOne/Many method was not expecting an array.
> fix(database): rawQuery throwing error on mongoose update methods
